In [1]:
import pandas as pd
import numpy as np
import json as js
from datetime import datetime

file_twitter = "./sample.txt"
file_keys = "./CU_Keywords.2013-01-25T15-36-29"

languages = ['English', 'Portuguese', 'Spanish']


def get_keywords(f_key_dict):
    dicts = {}
    for lag in languages:
        dicts[lag] = {}
    for l in open(f_key_dict):
        obj = js.loads(l)
        lag = obj['language']
        if lag in languages:
            #word = obj['text']
            lemma = obj['tokens'][0]['lemma']
            dicts[lag][lemma] = True
    return dicts


def get_features(obj, language, keywords):
    res = [key in obj['BasisEnrichment']['tokens'] for key in keywords]
    return [int(r) for r in res]
    
        
dicts = get_keywords(file_keys)

In [2]:
language = languages[1]
keywords = list(dicts[language].keys())
df_twitter = pd.DataFrame(columns=(keywords + ['date']))
lines = open(file_twitter).readlines()
for i in range(len(lines)):
    obj = js.loads(lines[i])
    if obj['embersGeoCode']['country'] == 'Brazil':
        df_twitter.loc[i] = get_features(obj,language,dicts[language]) + [datetime.strptime(obj['date'].split("T")[0],'%Y-%m-%d')]
df_aggregated = df_twitter.groupby("date").agg({key: np.sum for key in keywords})
days_range = (max(df_aggregated.index.values) - min(df_aggregated.index.values))/np.timedelta64(1, 'D')
days_indexes = [min(df_aggregated.index.values) + timedelta(days=i) for i in range(days_range)]

TypeError: range() integer end argument expected, got numpy.float64.

In [3]:
days_range

28.0

In [4]:
days_indexes = [min(df_aggregated.index.values) + timedelta(days=i) for i in range(int(days_range))]

NameError: name 'timedelta' is not defined

In [5]:
from datetime import timedelta

In [6]:
days_indexes = [min(df_aggregated.index.values) + timedelta(days=i) for i in range(int(days_range))]

TypeError: ufunc add cannot use operands with types dtype('<M8[ns]') and dtype('O')

In [7]:
min(df_aggregated.index.values)

numpy.datetime64('2014-12-02T19:00:00.000000000-0500')

In [8]:
days_indexes = [min(df_aggregated.index.values) + np.timedelta64(1,'D') for i in range(int(days_range))]

In [9]:
days_indexes

[numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500')]

In [10]:
days_indexes = [min(df_aggregated.index.values) + np.timedelta64(i,'D') for i in range(int(days_range))]

In [11]:
days_indexes

[numpy.datetime64('2014-12-02T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-04T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-05T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-06T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-07T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-08T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-09T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-10T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-11T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-12T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-13T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-14T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-15T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-16T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-17T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-18T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-19T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-20T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-21T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-22T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-23T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-24T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-25T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-26T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-27T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-28T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-29T19:00:00.000000000-0500')]

In [12]:
df_aggregated.index.values

array(['2014-12-02T19:00:00.000000000-0500',
       '2014-12-14T19:00:00.000000000-0500',
       '2014-12-15T19:00:00.000000000-0500',
       '2014-12-30T19:00:00.000000000-0500'], dtype='datetime64[ns]')

In [13]:
days_indexes = [min(df_aggregated.index.values) + np.timedelta64(i,'D') for i in range(int(days_range) + 1)]

In [14]:
days_indexes

[numpy.datetime64('2014-12-02T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-04T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-05T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-06T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-07T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-08T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-09T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-10T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-11T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-12T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-13T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-14T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-15T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-16T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-17T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-18T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-19T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-20T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-21T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-22T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-23T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-24T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-25T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-26T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-27T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-28T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-29T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-30T19:00:00.000000000-0500')]

In [15]:
new_index = [min(df_aggregated.index.values) + np.timedelta64(i,'D') for i in range(int(days_range) + 1)]
df_filled = df_aggregated.reindex(new_index)

In [16]:
df_filled

,medo,ataque,armar,emboscada,interrogatório,recrudescência,oposição,essencial,cooperativa,pobreza,...,guarani,vice,vigília,perseguição,perigo,relação,desgosto,promotor,rural,manter
date,,,,,,,,,,,,,,,,,,,,,
2014-12-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
new_index = [min(df_aggregated.index.values) + np.timedelta64(i,'D') for i in range(int(days_range) )]
df_filled = df_aggregated.reindex(new_index)

In [18]:
df_filled

,medo,ataque,armar,emboscada,interrogatório,recrudescência,oposição,essencial,cooperativa,pobreza,...,guarani,vice,vigília,perseguição,perigo,relação,desgosto,promotor,rural,manter
date,,,,,,,,,,,,,,,,,,,,,
2014-12-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_aggregated

,medo,ataque,armar,emboscada,interrogatório,recrudescência,oposição,essencial,cooperativa,pobreza,...,guarani,vice,vigília,perseguição,perigo,relação,desgosto,promotor,rural,manter
date,,,,,,,,,,,,,,,,,,,,,
2014-12-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
new_index = [min(df_aggregated.index.values) + np.timedelta64(i,'D') for i in range(int(days_range)+ 1)]
df_filled = df_aggregated.reindex(new_index)
df_filled

,medo,ataque,armar,emboscada,interrogatório,recrudescência,oposição,essencial,cooperativa,pobreza,...,guarani,vice,vigília,perseguição,perigo,relação,desgosto,promotor,rural,manter
date,,,,,,,,,,,,,,,,,,,,,
2014-12-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-12-31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
new_index

[numpy.datetime64('2014-12-02T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-03T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-04T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-05T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-06T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-07T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-08T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-09T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-10T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-11T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-12T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-13T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-14T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-15T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-16T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-17T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-18T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-19T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-20T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-21T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-22T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-23T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-24T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-25T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-26T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-27T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-28T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-29T19:00:00.000000000-0500'),
 numpy.datetime64('2014-12-30T19:00:00.000000000-0500')]

In [22]:
df_filled.fillna(0)

,medo,ataque,armar,emboscada,interrogatório,recrudescência,oposição,essencial,cooperativa,pobreza,...,guarani,vice,vigília,perseguição,perigo,relação,desgosto,promotor,rural,manter
date,,,,,,,,,,,,,,,,,,,,,
2014-12-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-05,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-06,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-08,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-09,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
file_gsr = "./gsrAll.json"

df_gsr = pd.DataFrame(columns=('date', 'country'))
lines = open(file_gsr).readlines()
for i in range(len(lines)):
    obj = js.loads(lines[i])
    if obj['location'][0] == 'Brazil':
        df_gsr.loc[i] = [obj['eventDate'],obj['location'][0]]

In [24]:
df_gsr

                      date country
93     2011-02-08T00:00:00  Brazil
109    2011-02-09T00:00:00  Brazil
148    2011-02-24T00:00:00  Brazil
230    2011-03-24T00:00:00  Brazil
232    2011-03-24T00:00:00  Brazil
395    2011-05-21T00:00:00  Brazil
519    2011-07-02T00:00:00  Brazil
620    2011-08-04T00:00:00  Brazil
628    2011-08-08T00:00:00  Brazil
633    2011-08-08T00:00:00  Brazil
637    2011-08-09T00:00:00  Brazil
692    2011-08-29T00:00:00  Brazil
727    2011-09-07T00:00:00  Brazil
746    2011-09-20T00:00:00  Brazil
763    2011-09-21T00:00:00  Brazil
771    2011-09-27T00:00:00  Brazil
870    2011-10-27T00:00:00  Brazil
909    2011-11-10T00:00:00  Brazil
992    2011-12-11T00:00:00  Brazil
1008   2011-12-16T00:00:00  Brazil
1029   2012-02-01T00:00:00  Brazil
1066   2012-01-10T00:00:00  Brazil
1128   2012-01-31T00:00:00  Brazil
1234   2012-03-01T00:00:00  Brazil
1239   2012-03-05T00:00:00  Brazil
1263   2012-03-08T00:00:00  Brazil
1295   2012-03-18T00:00:00  Brazil
1327   2012-03-28T00:00:00  Brazil
1328   2012-03-29T00:00:00  Brazil
1329   2012-03-29T00:00:00  Brazil
...                    ...     ...
26483  2015-01-23T00:00:00  Brazil
26484  2015-01-23T00:00:00  Brazil
26485  2015-01-23T00:00:00  Brazil
26486  2015-01-23T00:00:00  Brazil
26487  2015-01-23T00:00:00  Brazil
26488  2015-01-23T00:00:00  Brazil
26489  2015-01-23T00:00:00  Brazil
26490  2015-01-23T00:00:00  Brazil
26491  2015-01-23T00:00:00  Brazil
26492  2015-01-24T00:00:00  Brazil
26493  2015-01-25T00:00:00  Brazil
26494  2015-01-26T00:00:00  Brazil
26495  2015-01-26T00:00:00  Brazil
26496  2015-01-26T00:00:00  Brazil
26497  2015-01-27T00:00:00  Brazil
26498  2015-01-27T00:00:00  Brazil
26499  2015-01-27T00:00:00  Brazil
26500  2015-01-27T00:00:00  Brazil
26501  2015-01-27T00:00:00  Brazil
26502  2015-01-28T00:00:00  Brazil
26503  2015-01-28T00:00:00  Brazil
26504  2015-01-28T00:00:00  Brazil
26505  2015-01-28T00:00:00  Brazil
26506  2015-01-28T00:00:00  Brazil
26507  2015-01-28T00:00:00  Brazil
26508  2015-01-29T00:00:00  Brazil
26509  2015-01-29T00:00:00  Brazil
26510  2015-01-30T00:00:00  Brazil
26511  2015-01-30T00:00:00  Brazil
26512  2015-01-31T00:00:00  Brazil

[3777 rows x 2 columns]

In [25]:
for i in range(len(lines)):
    obj = js.loads(lines[i])
    if obj['location'][0] == 'Brazil':
        df_gsr.loc[i] = [datetime.strptime(obj['eventDate'].split("T")[0],'%Y-%m-%d'), 1]

In [26]:
df_gsr

                      date country
93     2011-02-08 00:00:00       1
109    2011-02-09 00:00:00       1
148    2011-02-24 00:00:00       1
230    2011-03-24 00:00:00       1
232    2011-03-24 00:00:00       1
395    2011-05-21 00:00:00       1
519    2011-07-02 00:00:00       1
620    2011-08-04 00:00:00       1
628    2011-08-08 00:00:00       1
633    2011-08-08 00:00:00       1
637    2011-08-09 00:00:00       1
692    2011-08-29 00:00:00       1
727    2011-09-07 00:00:00       1
746    2011-09-20 00:00:00       1
763    2011-09-21 00:00:00       1
771    2011-09-27 00:00:00       1
870    2011-10-27 00:00:00       1
909    2011-11-10 00:00:00       1
992    2011-12-11 00:00:00       1
1008   2011-12-16 00:00:00       1
1029   2012-02-01 00:00:00       1
1066   2012-01-10 00:00:00       1
1128   2012-01-31 00:00:00       1
1234   2012-03-01 00:00:00       1
1239   2012-03-05 00:00:00       1
1263   2012-03-08 00:00:00       1
1295   2012-03-18 00:00:00       1
1327   2012-03-28 00:00:00       1
1328   2012-03-29 00:00:00       1
1329   2012-03-29 00:00:00       1
...                    ...     ...
26483  2015-01-23 00:00:00       1
26484  2015-01-23 00:00:00       1
26485  2015-01-23 00:00:00       1
26486  2015-01-23 00:00:00       1
26487  2015-01-23 00:00:00       1
26488  2015-01-23 00:00:00       1
26489  2015-01-23 00:00:00       1
26490  2015-01-23 00:00:00       1
26491  2015-01-23 00:00:00       1
26492  2015-01-24 00:00:00       1
26493  2015-01-25 00:00:00       1
26494  2015-01-26 00:00:00       1
26495  2015-01-26 00:00:00       1
26496  2015-01-26 00:00:00       1
26497  2015-01-27 00:00:00       1
26498  2015-01-27 00:00:00       1
26499  2015-01-27 00:00:00       1
26500  2015-01-27 00:00:00       1
26501  2015-01-27 00:00:00       1
26502  2015-01-28 00:00:00       1
26503  2015-01-28 00:00:00       1
26504  2015-01-28 00:00:00       1
26505  2015-01-28 00:00:00       1
26506  2015-01-28 00:00:00       1
26507  2015-01-28 00:00:00       1
26508  2015-01-29 00:00:00       1
26509  2015-01-29 00:00:00       1
26510  2015-01-30 00:00:00       1
26511  2015-01-30 00:00:00       1
26512  2015-01-31 00:00:00       1

[3777 rows x 2 columns]

In [27]:
[min(df_aggregated.index.values)]

[numpy.datetime64('2014-12-02T19:00:00.000000000-0500')]

In [28]:
min_date = np.datetime64('2014-01-01')

In [29]:
[min(df_aggregated.index.values)] > min_date

TypeError: Cannot cast ufunc less input from dtype('<M8[D]') to dtype('<M8[ns]') with casting rule 'same_kind'

In [30]:
min_date

numpy.datetime64('2014-01-01')

In [31]:
2_date = min(df_aggregated.index.values) + np.timedelta64(i,'D')

SyntaxError: invalid syntax (<ipython-input-31-be5494ac14c4>, line 1)

In [32]:
another_day = min(df_aggregated.index.values) + np.timedelta64(i,'D')

In [33]:
min_date < another_day

TypeError: Cannot cast ufunc less input from dtype('<M8[D]') to dtype('<M8[ns]') with casting rule 'same_kind'

In [34]:
another_day

numpy.datetime64('2089-03-31T20:00:00.000000000-0400')

In [35]:
min_date

numpy.datetime64('2014-01-01')

In [36]:
another_day

numpy.datetime64('2089-03-31T20:00:00.000000000-0400')

In [37]:
min_date

numpy.datetime64('2014-01-01')

In [38]:
another_day = min(df_aggregated.index.values) + np.timedelta64(1,'D')

In [39]:
another_day

numpy.datetime64('2014-12-03T19:00:00.000000000-0500')

In [40]:
min_date < another_day

TypeError: Cannot cast ufunc less input from dtype('<M8[D]') to dtype('<M8[ns]') with casting rule 'same_kind'

In [41]:
min_date.astype(datetime) < another_day.astype(datetime)

TypeError: can't compare datetime.date to long

In [42]:
another_day.astype(datetime)

1417651200000000000L

In [43]:
min_date.astype(datetime)

datetime.date(2014, 1, 1)

In [44]:
min_date

numpy.datetime64('2014-01-01')

In [45]:
min_date

numpy.datetime64('2014-01-01')

In [46]:
another_day = min_date + np.timedelta64(1,'D')

In [47]:
another_day

numpy.datetime64('2014-01-02')

In [48]:
numpy.datetime64('2014-01-02')

NameError: name 'numpy' is not defined

In [49]:
np.datetime64('2014-01-02')

numpy.datetime64('2014-01-02')

In [50]:
min_date < another_day

True

In [51]:
min_date = np.datetime64('2014-01-01')
max_date = np.datetime64('2014-12-31')

In [52]:
df_gsr_selected = df_gsr[(df_gsr.date >= min_date)&(df_gsr.date <= max_date)]

TypeError: can't compare datetime.datetime to numpy.datetime64

In [53]:
min_date = datetime.date(2014,1,1)
max_date = np.datetime64(2014,12,31)

TypeError: descriptor 'date' requires a 'datetime.datetime' object but received a 'int'

In [54]:
min_date = datetime.date(2014,1,1)
max_date = datetime.date(2014,12,31)

TypeError: descriptor 'date' requires a 'datetime.datetime' object but received a 'int'

In [55]:
from datetime import datetime,timedelta,date

In [56]:
min_date = date(2014,1,1)
max_date = date(2014,12,31)

In [57]:
df_gsr_selected = df_gsr[(df_gsr.date >= min_date)&(df_gsr.date <= max_date)]

TypeError: can't compare datetime.datetime to datetime.date

In [58]:
min_date = datetime(2014,1,1)

In [59]:
min_date = datetime(2014,1,1)
max_date = datetime(2014,12,31)

In [60]:
df_gsr_selected = df_gsr[(df_gsr.date >= min_date)&(df_gsr.date <= max_date)]

In [61]:
df_gsr_selected

                      date country
14327  2014-01-01 00:00:00       1
14328  2014-01-02 00:00:00       1
14329  2014-01-03 00:00:00       1
14330  2014-01-03 00:00:00       1
14331  2014-01-02 00:00:00       1
14332  2014-01-03 00:00:00       1
14333  2014-01-04 00:00:00       1
14334  2014-01-04 00:00:00       1
14335  2014-01-05 00:00:00       1
14336  2014-01-05 00:00:00       1
14337  2014-01-05 00:00:00       1
14338  2014-01-06 00:00:00       1
14339  2014-01-06 00:00:00       1
14340  2014-01-06 00:00:00       1
14341  2014-01-06 00:00:00       1
14342  2014-01-07 00:00:00       1
14343  2014-01-07 00:00:00       1
14344  2014-01-07 00:00:00       1
14345  2014-01-07 00:00:00       1
14346  2014-01-07 00:00:00       1
14347  2014-01-07 00:00:00       1
14348  2014-01-07 00:00:00       1
14349  2014-01-08 00:00:00       1
14350  2014-01-08 00:00:00       1
14351  2014-01-09 00:00:00       1
14352  2014-01-09 00:00:00       1
14353  2014-01-09 00:00:00       1
14354  2014-01-10 00:00:00       1
14355  2014-01-10 00:00:00       1
14356  2014-01-10 00:00:00       1
...                    ...     ...
25614  2014-12-14 00:00:00       1
25615  2014-12-14 00:00:00       1
25616  2014-12-15 00:00:00       1
25617  2014-12-15 00:00:00       1
25618  2014-12-15 00:00:00       1
25619  2014-12-16 00:00:00       1
25620  2014-12-16 00:00:00       1
25621  2014-12-16 00:00:00       1
25622  2014-12-16 00:00:00       1
25623  2014-12-16 00:00:00       1
25624  2014-12-16 00:00:00       1
25625  2014-12-16 00:00:00       1
25626  2014-12-17 00:00:00       1
25627  2014-12-17 00:00:00       1
25628  2014-12-17 00:00:00       1
25629  2014-12-17 00:00:00       1
25630  2014-12-17 00:00:00       1
25631  2014-12-17 00:00:00       1
25632  2014-12-17 00:00:00       1
25633  2014-12-17 00:00:00       1
25634  2014-12-17 00:00:00       1
25635  2014-12-18 00:00:00       1
25636  2014-12-19 00:00:00       1
25637  2014-12-22 00:00:00       1
25638  2014-12-22 00:00:00       1
25639  2014-12-22 00:00:00       1
25640  2014-12-22 00:00:00       1
25641  2014-12-26 00:00:00       1
25642  2014-12-29 00:00:00       1
26317  2014-12-31 00:00:00       1

[1635 rows x 2 columns]

In [62]:
max_date - min_date

datetime.timedelta(364)

In [63]:
df_gsr_aggregated = df_gsr_selected.groupby("date").agg({event:1})

NameError: name 'event' is not defined

In [64]:
df_gsr_selected

                      date country
14327  2014-01-01 00:00:00       1
14328  2014-01-02 00:00:00       1
14329  2014-01-03 00:00:00       1
14330  2014-01-03 00:00:00       1
14331  2014-01-02 00:00:00       1
14332  2014-01-03 00:00:00       1
14333  2014-01-04 00:00:00       1
14334  2014-01-04 00:00:00       1
14335  2014-01-05 00:00:00       1
14336  2014-01-05 00:00:00       1
14337  2014-01-05 00:00:00       1
14338  2014-01-06 00:00:00       1
14339  2014-01-06 00:00:00       1
14340  2014-01-06 00:00:00       1
14341  2014-01-06 00:00:00       1
14342  2014-01-07 00:00:00       1
14343  2014-01-07 00:00:00       1
14344  2014-01-07 00:00:00       1
14345  2014-01-07 00:00:00       1
14346  2014-01-07 00:00:00       1
14347  2014-01-07 00:00:00       1
14348  2014-01-07 00:00:00       1
14349  2014-01-08 00:00:00       1
14350  2014-01-08 00:00:00       1
14351  2014-01-09 00:00:00       1
14352  2014-01-09 00:00:00       1
14353  2014-01-09 00:00:00       1
14354  2014-01-10 00:00:00       1
14355  2014-01-10 00:00:00       1
14356  2014-01-10 00:00:00       1
...                    ...     ...
25614  2014-12-14 00:00:00       1
25615  2014-12-14 00:00:00       1
25616  2014-12-15 00:00:00       1
25617  2014-12-15 00:00:00       1
25618  2014-12-15 00:00:00       1
25619  2014-12-16 00:00:00       1
25620  2014-12-16 00:00:00       1
25621  2014-12-16 00:00:00       1
25622  2014-12-16 00:00:00       1
25623  2014-12-16 00:00:00       1
25624  2014-12-16 00:00:00       1
25625  2014-12-16 00:00:00       1
25626  2014-12-17 00:00:00       1
25627  2014-12-17 00:00:00       1
25628  2014-12-17 00:00:00       1
25629  2014-12-17 00:00:00       1
25630  2014-12-17 00:00:00       1
25631  2014-12-17 00:00:00       1
25632  2014-12-17 00:00:00       1
25633  2014-12-17 00:00:00       1
25634  2014-12-17 00:00:00       1
25635  2014-12-18 00:00:00       1
25636  2014-12-19 00:00:00       1
25637  2014-12-22 00:00:00       1
25638  2014-12-22 00:00:00       1
25639  2014-12-22 00:00:00       1
25640  2014-12-22 00:00:00       1
25641  2014-12-26 00:00:00       1
25642  2014-12-29 00:00:00       1
26317  2014-12-31 00:00:00       1

[1635 rows x 2 columns]

In [65]:
df_gsr = pd.DataFrame(columns=('date', 'event'))
Lines = open(file_gsr).readlines()
for i in range(len(lines)):
    obj = js.loads(lines[i])
    if obj['location'][0] == 'Brazil':
        df_gsr.loc[i] = [datetime.strptime(obj['eventDate'].split("T")[0],'%Y-%m-%d'), 1]

In [66]:
df_gsr_selected = df_gsr[(df_gsr.date >= min_date)&(df_gsr.date <= max_date)]

In [67]:
df_gsr_selected = df_gsr[(df_gsr.date >= min_date)&(df_gsr.date <= max_date)]

In [68]:
df_gsr_selected

            date  event
14327 2014-01-01      1
14328 2014-01-02      1
14329 2014-01-03      1
14330 2014-01-03      1
14331 2014-01-02      1
14332 2014-01-03      1
14333 2014-01-04      1
14334 2014-01-04      1
14335 2014-01-05      1
14336 2014-01-05      1
14337 2014-01-05      1
14338 2014-01-06      1
14339 2014-01-06      1
14340 2014-01-06      1
14341 2014-01-06      1
14342 2014-01-07      1
14343 2014-01-07      1
14344 2014-01-07      1
14345 2014-01-07      1
14346 2014-01-07      1
14347 2014-01-07      1
14348 2014-01-07      1
14349 2014-01-08      1
14350 2014-01-08      1
14351 2014-01-09      1
14352 2014-01-09      1
14353 2014-01-09      1
14354 2014-01-10      1
14355 2014-01-10      1
14356 2014-01-10      1
...          ...    ...
25614 2014-12-14      1
25615 2014-12-14      1
25616 2014-12-15      1
25617 2014-12-15      1
25618 2014-12-15      1
25619 2014-12-16      1
25620 2014-12-16      1
25621 2014-12-16      1
25622 2014-12-16      1
25623 2014-12-16      1
25624 2014-12-16      1
25625 2014-12-16      1
25626 2014-12-17      1
25627 2014-12-17      1
25628 2014-12-17      1
25629 2014-12-17      1
25630 2014-12-17      1
25631 2014-12-17      1
25632 2014-12-17      1
25633 2014-12-17      1
25634 2014-12-17      1
25635 2014-12-18      1
25636 2014-12-19      1
25637 2014-12-22      1
25638 2014-12-22      1
25639 2014-12-22      1
25640 2014-12-22      1
25641 2014-12-26      1
25642 2014-12-29      1
26317 2014-12-31      1

[1635 rows x 2 columns]

In [69]:
df_gsr_aggregated = df_gsr_selected.groupby("date").agg({event:1})

NameError: name 'event' is not defined

In [70]:
df_gsr_aggregated = df_gsr_selected.groupby("date").agg({'event':1})

TypeError: 'int' object is not callable

In [71]:
df_gsr_aggregated = df_gsr_selected.groupby("date").agg({'event':lambda x: 1})

In [72]:
df_gsr_aggregated

            event
date
2014-01-01      1
2014-01-02      1
2014-01-03      1
2014-01-04      1
2014-01-05      1
2014-01-06      1
2014-01-07      1
2014-01-08      1
2014-01-09      1
2014-01-10      1
2014-01-11      1
2014-01-12      1
2014-01-13      1
2014-01-14      1
2014-01-15      1
2014-01-16      1
2014-01-17      1
2014-01-18      1
2014-01-19      1
2014-01-20      1
2014-01-21      1
2014-01-22      1
2014-01-23      1
2014-01-24      1
2014-01-25      1
2014-01-26      1
2014-01-27      1
2014-01-28      1
2014-01-29      1
2014-01-30      1
...           ...
2014-11-25      1
2014-11-26      1
2014-11-27      1
2014-11-28      1
2014-11-29      1
2014-11-30      1
2014-12-01      1
2014-12-02      1
2014-12-03      1
2014-12-04      1
2014-12-05      1
2014-12-06      1
2014-12-07      1
2014-12-08      1
2014-12-09      1
2014-12-10      1
2014-12-11      1
2014-12-12      1
2014-12-13      1
2014-12-14      1
2014-12-15      1
2014-12-16      1
2014-12-17      1
2014-12-18      1
2014-12-19      1
2014-12-22      1
2014-12-24      1
2014-12-26      1
2014-12-29      1
2014-12-31      1

[343 rows x 1 columns]

In [73]:
max_date - min_date

datetime.timedelta(364)

In [74]:
interval = max_date - min_date

In [75]:
interval.days

364

In [76]:
days_range = (max_date - min_date)

In [77]:
days_range

datetime.timedelta(364)

In [78]:
days_range = (max_date - min_date).days

In [79]:
days_range

364

In [80]:
[min_date + timedelta(days = i) for i in (max_date - min_date).days]

TypeError: 'int' object is not iterable

In [81]:
[min_date + timedelta(days = i) for i in range((max_date - min_date).days + 1)]

[datetime.datetime(2014, 1, 1, 0, 0),
 datetime.datetime(2014, 1, 2, 0, 0),
 datetime.datetime(2014, 1, 3, 0, 0),
 datetime.datetime(2014, 1, 4, 0, 0),
 datetime.datetime(2014, 1, 5, 0, 0),
 datetime.datetime(2014, 1, 6, 0, 0),
 datetime.datetime(2014, 1, 7, 0, 0),
 datetime.datetime(2014, 1, 8, 0, 0),
 datetime.datetime(2014, 1, 9, 0, 0),
 datetime.datetime(2014, 1, 10, 0, 0),
 datetime.datetime(2014, 1, 11, 0, 0),
 datetime.datetime(2014, 1, 12, 0, 0),
 datetime.datetime(2014, 1, 13, 0, 0),
 datetime.datetime(2014, 1, 14, 0, 0),
 datetime.datetime(2014, 1, 15, 0, 0),
 datetime.datetime(2014, 1, 16, 0, 0),
 datetime.datetime(2014, 1, 17, 0, 0),
 datetime.datetime(2014, 1, 18, 0, 0),
 datetime.datetime(2014, 1, 19, 0, 0),
 datetime.datetime(2014, 1, 20, 0, 0),
 datetime.datetime(2014, 1, 21, 0, 0),
 datetime.datetime(2014, 1, 22, 0, 0),
 datetime.datetime(2014, 1, 23, 0, 0),
 datetime.datetime(2014, 1, 24, 0, 0),
 datetime.datetime(2014, 1, 25, 0, 0),
 datetime.datetime(2014, 1, 26, 0, 0),
 datetime.datetime(2014, 1, 27, 0, 0),
 datetime.datetime(2014, 1, 28, 0, 0),
 datetime.datetime(2014, 1, 29, 0, 0),
 datetime.datetime(2014, 1, 30, 0, 0),
 datetime.datetime(2014, 1, 31, 0, 0),
 datetime.datetime(2014, 2, 1, 0, 0),
 datetime.datetime(2014, 2, 2, 0, 0),
 datetime.datetime(2014, 2, 3, 0, 0),
 datetime.datetime(2014, 2, 4, 0, 0),
 datetime.datetime(2014, 2, 5, 0, 0),
 datetime.datetime(2014, 2, 6, 0, 0),
 datetime.datetime(2014, 2, 7, 0, 0),
 datetime.datetime(2014, 2, 8, 0, 0),
 datetime.datetime(2014, 2, 9, 0, 0),
 datetime.datetime(2014, 2, 10, 0, 0),
 datetime.datetime(2014, 2, 11, 0, 0),
 datetime.datetime(2014, 2, 12, 0, 0),
 datetime.datetime(2014, 2, 13, 0, 0),
 datetime.datetime(2014, 2, 14, 0, 0),
 datetime.datetime(2014, 2, 15, 0, 0),
 datetime.datetime(2014, 2, 16, 0, 0),
 datetime.datetime(2014, 2, 17, 0, 0),
 datetime.datetime(2014, 2, 18, 0, 0),
 datetime.datetime(2014, 2, 19, 0, 0),
 datetime.datetime(2014, 2, 20, 0, 0),
 datetime.datetime(2014, 2, 21, 0, 0),
 datetime.datetime(2014, 2, 22, 0, 0),
 datetime.datetime(2014, 2, 23, 0, 0),
 datetime.datetime(2014, 2, 24, 0, 0),
 datetime.datetime(2014, 2, 25, 0, 0),
 datetime.datetime(2014, 2, 26, 0, 0),
 datetime.datetime(2014, 2, 27, 0, 0),
 datetime.datetime(2014, 2, 28, 0, 0),
 datetime.datetime(2014, 3, 1, 0, 0),
 datetime.datetime(2014, 3, 2, 0, 0),
 datetime.datetime(2014, 3, 3, 0, 0),
 datetime.datetime(2014, 3, 4, 0, 0),
 datetime.datetime(2014, 3, 5, 0, 0),
 datetime.datetime(2014, 3, 6, 0, 0),
 datetime.datetime(2014, 3, 7, 0, 0),
 datetime.datetime(2014, 3, 8, 0, 0),
 datetime.datetime(2014, 3, 9, 0, 0),
 datetime.datetime(2014, 3, 10, 0, 0),
 datetime.datetime(2014, 3, 11, 0, 0),
 datetime.datetime(2014, 3, 12, 0, 0),
 datetime.datetime(2014, 3, 13, 0, 0),
 datetime.datetime(2014, 3, 14, 0, 0),
 datetime.datetime(2014, 3, 15, 0, 0),
 datetime.datetime(2014, 3, 16, 0, 0),
 datetime.datetime(2014, 3, 17, 0, 0),
 datetime.datetime(2014, 3, 18, 0, 0),
 datetime.datetime(2014, 3, 19, 0, 0),
 datetime.datetime(2014, 3, 20, 0, 0),
 datetime.datetime(2014, 3, 21, 0, 0),
 datetime.datetime(2014, 3, 22, 0, 0),
 datetime.datetime(2014, 3, 23, 0, 0),
 datetime.datetime(2014, 3, 24, 0, 0),
 datetime.datetime(2014, 3, 25, 0, 0),
 datetime.datetime(2014, 3, 26, 0, 0),
 datetime.datetime(2014, 3, 27, 0, 0),
 datetime.datetime(2014, 3, 28, 0, 0),
 datetime.datetime(2014, 3, 29, 0, 0),
 datetime.datetime(2014, 3, 30, 0, 0),
 datetime.datetime(2014, 3, 31, 0, 0),
 datetime.datetime(2014, 4, 1, 0, 0),
 datetime.datetime(2014, 4, 2, 0, 0),
 datetime.datetime(2014, 4, 3, 0, 0),
 datetime.datetime(2014, 4, 4, 0, 0),
 datetime.datetime(2014, 4, 5, 0, 0),
 datetime.datetime(2014, 4, 6, 0, 0),
 datetime.datetime(2014, 4, 7, 0, 0),
 datetime.datetime(2014, 4, 8, 0, 0),
 datetime.datetime(2014, 4, 9, 0, 0),
 datetime.datetime(2014, 4, 10, 0, 0),
 datetime.datetime(2014, 4, 11, 0, 0),
 datetime.datetime(2014, 4, 12, 0, 0),
 datetime.datetime(2014, 4, 13, 0, 0),
 datetime.datetime(2014, 4, 14, 0, 0),
 datetime.datetime(2014, 4, 15, 0, 0),
 datetime.datetime(2014, 4, 16, 0, 0),
 datetime.datetime(2014, 4, 17, 0, 0),
 datetime.datetime(2014, 4, 18, 0, 0),
 datetime.datetime(2014, 4, 19, 0, 0),
 datetime.datetime(2014, 4, 20, 0, 0),
 datetime.datetime(2014, 4, 21, 0, 0),
 datetime.datetime(2014, 4, 22, 0, 0),
 datetime.datetime(2014, 4, 23, 0, 0),
 datetime.datetime(2014, 4, 24, 0, 0),
 datetime.datetime(2014, 4, 25, 0, 0),
 datetime.datetime(2014, 4, 26, 0, 0),
 datetime.datetime(2014, 4, 27, 0, 0),
 datetime.datetime(2014, 4, 28, 0, 0),
 datetime.datetime(2014, 4, 29, 0, 0),
 datetime.datetime(2014, 4, 30, 0, 0),
 datetime.datetime(2014, 5, 1, 0, 0),
 datetime.datetime(2014, 5, 2, 0, 0),
 datetime.datetime(2014, 5, 3, 0, 0),
 datetime.datetime(2014, 5, 4, 0, 0),
 datetime.datetime(2014, 5, 5, 0, 0),
 datetime.datetime(2014, 5, 6, 0, 0),
 datetime.datetime(2014, 5, 7, 0, 0),
 datetime.datetime(2014, 5, 8, 0, 0),
 datetime.datetime(2014, 5, 9, 0, 0),
 datetime.datetime(2014, 5, 10, 0, 0),
 datetime.datetime(2014, 5, 11, 0, 0),
 datetime.datetime(2014, 5, 12, 0, 0),
 datetime.datetime(2014, 5, 13, 0, 0),
 datetime.datetime(2014, 5, 14, 0, 0),
 datetime.datetime(2014, 5, 15, 0, 0),
 datetime.datetime(2014, 5, 16, 0, 0),
 datetime.datetime(2014, 5, 17, 0, 0),
 datetime.datetime(2014, 5, 18, 0, 0),
 datetime.datetime(2014, 5, 19, 0, 0),
 datetime.datetime(2014, 5, 20, 0, 0),
 datetime.datetime(2014, 5, 21, 0, 0),
 datetime.datetime(2014, 5, 22, 0, 0),
 datetime.datetime(2014, 5, 23, 0, 0),
 datetime.datetime(2014, 5, 24, 0, 0),
 datetime.datetime(2014, 5, 25, 0, 0),
 datetime.datetime(2014, 5, 26, 0, 0),
 datetime.datetime(2014, 5, 27, 0, 0),
 datetime.datetime(2014, 5, 28, 0, 0),
 datetime.datetime(2014, 5, 29, 0, 0),
 datetime.datetime(2014, 5, 30, 0, 0),
 datetime.datetime(2014, 5, 31, 0, 0),
 datetime.datetime(2014, 6, 1, 0, 0),
 datetime.datetime(2014, 6, 2, 0, 0),
 datetime.datetime(2014, 6, 3, 0, 0),
 datetime.datetime(2014, 6, 4, 0, 0),
 datetime.datetime(2014, 6, 5, 0, 0),
 datetime.datetime(2014, 6, 6, 0, 0),
 datetime.datetime(2014, 6, 7, 0, 0),
 datetime.datetime(2014, 6, 8, 0, 0),
 datetime.datetime(2014, 6, 9, 0, 0),
 datetime.datetime(2014, 6, 10, 0, 0),
 datetime.datetime(2014, 6, 11, 0, 0),
 datetime.datetime(2014, 6, 12, 0, 0),
 datetime.datetime(2014, 6, 13, 0, 0),
 datetime.datetime(2014, 6, 14, 0, 0),
 datetime.datetime(2014, 6, 15, 0, 0),
 datetime.datetime(2014, 6, 16, 0, 0),
 datetime.datetime(2014, 6, 17, 0, 0),
 datetime.datetime(2014, 6, 18, 0, 0),
 datetime.datetime(2014, 6, 19, 0, 0),
 datetime.datetime(2014, 6, 20, 0, 0),
 datetime.datetime(2014, 6, 21, 0, 0),
 datetime.datetime(2014, 6, 22, 0, 0),
 datetime.datetime(2014, 6, 23, 0, 0),
 datetime.datetime(2014, 6, 24, 0, 0),
 datetime.datetime(2014, 6, 25, 0, 0),
 datetime.datetime(2014, 6, 26, 0, 0),
 datetime.datetime(2014, 6, 27, 0, 0),
 datetime.datetime(2014, 6, 28, 0, 0),
 datetime.datetime(2014, 6, 29, 0, 0),
 datetime.datetime(2014, 6, 30, 0, 0),
 datetime.datetime(2014, 7, 1, 0, 0),
 datetime.datetime(2014, 7, 2, 0, 0),
 datetime.datetime(2014, 7, 3, 0, 0),
 datetime.datetime(2014, 7, 4, 0, 0),
 datetime.datetime(2014, 7, 5, 0, 0),
 datetime.datetime(2014, 7, 6, 0, 0),
 datetime.datetime(2014, 7, 7, 0, 0),
 datetime.datetime(2014, 7, 8, 0, 0),
 datetime.datetime(2014, 7, 9, 0, 0),
 datetime.datetime(2014, 7, 10, 0, 0),
 datetime.datetime(2014, 7, 11, 0, 0),
 datetime.datetime(2014, 7, 12, 0, 0),
 datetime.datetime(2014, 7, 13, 0, 0),
 datetime.datetime(2014, 7, 14, 0, 0),
 datetime.datetime(2014, 7, 15, 0, 0),
 datetime.datetime(2014, 7, 16, 0, 0),
 datetime.datetime(2014, 7, 17, 0, 0),
 datetime.datetime(2014, 7, 18, 0, 0),
 datetime.datetime(2014, 7, 19, 0, 0),
 datetime.datetime(2014, 7, 20, 0, 0),
 datetime.datetime(2014, 7, 21, 0, 0),
 datetime.datetime(2014, 7, 22, 0, 0),
 datetime.datetime(2014, 7, 23, 0, 0),
 datetime.datetime(2014, 7, 24, 0, 0),
 datetime.datetime(2014, 7, 25, 0, 0),
 datetime.datetime(2014, 7, 26, 0, 0),
 datetime.datetime(2014, 7, 27, 0, 0),
 datetime.datetime(2014, 7, 28, 0, 0),
 datetime.datetime(2014, 7, 29, 0, 0),
 datetime.datetime(2014, 7, 30, 0, 0),
 datetime.datetime(2014, 7, 31, 0, 0),
 datetime.datetime(2014, 8, 1, 0, 0),
 datetime.datetime(2014, 8, 2, 0, 0),
 datetime.datetime(2014, 8, 3, 0, 0),
 datetime.datetime(2014, 8, 4, 0, 0),
 datetime.datetime(2014, 8, 5, 0, 0),
 datetime.datetime(2014, 8, 6, 0, 0),
 datetime.datetime(2014, 8, 7, 0, 0),
 datetime.datetime(2014, 8, 8, 0, 0),
 datetime.datetime(2014, 8, 9, 0, 0),
 datetime.datetime(2014, 8, 10, 0, 0),
 datetime.datetime(2014, 8, 11, 0, 0),
 datetime.datetime(2014, 8, 12, 0, 0),
 datetime.datetime(2014, 8, 13, 0, 0),
 datetime.datetime(2014, 8, 14, 0, 0),
 datetime.datetime(2014, 8, 15, 0, 0),
 datetime.datetime(2014, 8, 16, 0, 0),
 datetime.datetime(2014, 8, 17, 0, 0),
 datetime.datetime(2014, 8, 18, 0, 0),
 datetime.datetime(2014, 8, 19, 0, 0),
 datetime.datetime(2014, 8, 20, 0, 0),
 datetime.datetime(2014, 8, 21, 0, 0),
 datetime.datetime(2014, 8, 22, 0, 0),
 datetime.datetime(2014, 8, 23, 0, 0),
 datetime.datetime(2014, 8, 24, 0, 0),
 datetime.datetime(2014, 8, 25, 0, 0),
 datetime.datetime(2014, 8, 26, 0, 0),
 datetime.datetime(2014, 8, 27, 0, 0),
 datetime.datetime(2014, 8, 28, 0, 0),
 datetime.datetime(2014, 8, 29, 0, 0),
 datetime.datetime(2014, 8, 30, 0, 0),
 datetime.datetime(2014, 8, 31, 0, 0),
 datetime.datetime(2014, 9, 1, 0, 0),
 datetime.datetime(2014, 9, 2, 0, 0),
 datetime.datetime(2014, 9, 3, 0, 0),
 datetime.datetime(2014, 9, 4, 0, 0),
 datetime.datetime(2014, 9, 5, 0, 0),
 datetime.datetime(2014, 9, 6, 0, 0),
 datetime.datetime(2014, 9, 7, 0, 0),
 datetime.datetime(2014, 9, 8, 0, 0),
 datetime.datetime(2014, 9, 9, 0, 0),
 datetime.datetime(2014, 9, 10, 0, 0),
 datetime.datetime(2014, 9, 11, 0, 0),
 datetime.datetime(2014, 9, 12, 0, 0),
 datetime.datetime(2014, 9, 13, 0, 0),
 datetime.datetime(2014, 9, 14, 0, 0),
 datetime.datetime(2014, 9, 15, 0, 0),
 datetime.datetime(2014, 9, 16, 0, 0),
 datetime.datetime(2014, 9, 17, 0, 0),
 datetime.datetime(2014, 9, 18, 0, 0),
 datetime.datetime(2014, 9, 19, 0, 0),
 datetime.datetime(2014, 9, 20, 0, 0),
 datetime.datetime(2014, 9, 21, 0, 0),
 datetime.datetime(2014, 9, 22, 0, 0),
 datetime.datetime(2014, 9, 23, 0, 0),
 datetime.datetime(2014, 9, 24, 0, 0),
 datetime.datetime(2014, 9, 25, 0, 0),
 datetime.datetime(2014, 9, 26, 0, 0),
 datetime.datetime(2014, 9, 27, 0, 0),
 datetime.datetime(2014, 9, 28, 0, 0),
 datetime.datetime(2014, 9, 29, 0, 0),
 datetime.datetime(2014, 9, 30, 0, 0),
 datetime.datetime(2014, 10, 1, 0, 0),
 datetime.datetime(2014, 10, 2, 0, 0),
 datetime.datetime(2014, 10, 3, 0, 0),
 datetime.datetime(2014, 10, 4, 0, 0),
 datetime.datetime(2014, 10, 5, 0, 0),
 datetime.datetime(2014, 10, 6, 0, 0),
 datetime.datetime(2014, 10, 7, 0, 0),
 datetime.datetime(2014, 10, 8, 0, 0),
 datetime.datetime(2014, 10, 9, 0, 0),
 datetime.datetime(2014, 10, 10, 0, 0),
 datetime.datetime(2014, 10, 11, 0, 0),
 datetime.datetime(2014, 10, 12, 0, 0),
 datetime.datetime(2014, 10, 13, 0, 0),
 datetime.datetime(2014, 10, 14, 0, 0),
 datetime.datetime(2014, 10, 15, 0, 0),
 datetime.datetime(2014, 10, 16, 0, 0),
 datetime.datetime(2014, 10, 17, 0, 0),
 datetime.datetime(2014, 10, 18, 0, 0),
 datetime.datetime(2014, 10, 19, 0, 0),
 datetime.datetime(2014, 10, 20, 0, 0),
 datetime.datetime(2014, 10, 21, 0, 0),
 datetime.datetime(2014, 10, 22, 0, 0),
 datetime.datetime(2014, 10, 23, 0, 0),
 datetime.datetime(2014, 10, 24, 0, 0),
 datetime.datetime(2014, 10, 25, 0, 0),
 datetime.datetime(2014, 10, 26, 0, 0),
 datetime.datetime(2014, 10, 27, 0, 0),
 datetime.datetime(2014, 10, 28, 0, 0),
 datetime.datetime(2014, 10, 29, 0, 0),
 datetime.datetime(2014, 10, 30, 0, 0),
 datetime.datetime(2014, 10, 31, 0, 0),
 datetime.datetime(2014, 11, 1, 0, 0),
 datetime.datetime(2014, 11, 2, 0, 0),
 datetime.datetime(2014, 11, 3, 0, 0),
 datetime.datetime(2014, 11, 4, 0, 0),
 datetime.datetime(2014, 11, 5, 0, 0),
 datetime.datetime(2014, 11, 6, 0, 0),
 datetime.datetime(2014, 11, 7, 0, 0),
 datetime.datetime(2014, 11, 8, 0, 0),
 datetime.datetime(2014, 11, 9, 0, 0),
 datetime.datetime(2014, 11, 10, 0, 0),
 datetime.datetime(2014, 11, 11, 0, 0),
 datetime.datetime(2014, 11, 12, 0, 0),
 datetime.datetime(2014, 11, 13, 0, 0),
 datetime.datetime(2014, 11, 14, 0, 0),
 datetime.datetime(2014, 11, 15, 0, 0),
 datetime.datetime(2014, 11, 16, 0, 0),
 datetime.datetime(2014, 11, 17, 0, 0),
 datetime.datetime(2014, 11, 18, 0, 0),
 datetime.datetime(2014, 11, 19, 0, 0),
 datetime.datetime(2014, 11, 20, 0, 0),
 datetime.datetime(2014, 11, 21, 0, 0),
 datetime.datetime(2014, 11, 22, 0, 0),
 datetime.datetime(2014, 11, 23, 0, 0),
 datetime.datetime(2014, 11, 24, 0, 0),
 datetime.datetime(2014, 11, 25, 0, 0),
 datetime.datetime(2014, 11, 26, 0, 0),
 datetime.datetime(2014, 11, 27, 0, 0),
 datetime.datetime(2014, 11, 28, 0, 0),
 datetime.datetime(2014, 11, 29, 0, 0),
 datetime.datetime(2014, 11, 30, 0, 0),
 datetime.datetime(2014, 12, 1, 0, 0),
 datetime.datetime(2014, 12, 2, 0, 0),
 datetime.datetime(2014, 12, 3, 0, 0),
 datetime.datetime(2014, 12, 4, 0, 0),
 datetime.datetime(2014, 12, 5, 0, 0),
 datetime.datetime(2014, 12, 6, 0, 0),
 datetime.datetime(2014, 12, 7, 0, 0),
 datetime.datetime(2014, 12, 8, 0, 0),
 datetime.datetime(2014, 12, 9, 0, 0),
 datetime.datetime(2014, 12, 10, 0, 0),
 datetime.datetime(2014, 12, 11, 0, 0),
 datetime.datetime(2014, 12, 12, 0, 0),
 datetime.datetime(2014, 12, 13, 0, 0),
 datetime.datetime(2014, 12, 14, 0, 0),
 datetime.datetime(2014, 12, 15, 0, 0),
 datetime.datetime(2014, 12, 16, 0, 0),
 datetime.datetime(2014, 12, 17, 0, 0),
 datetime.datetime(2014, 12, 18, 0, 0),
 datetime.datetime(2014, 12, 19, 0, 0),
 datetime.datetime(2014, 12, 20, 0, 0),
 datetime.datetime(2014, 12, 21, 0, 0),
 datetime.datetime(2014, 12, 22, 0, 0),
 datetime.datetime(2014, 12, 23, 0, 0),
 datetime.datetime(2014, 12, 24, 0, 0),
 datetime.datetime(2014, 12, 25, 0, 0),
 datetime.datetime(2014, 12, 26, 0, 0),
 datetime.datetime(2014, 12, 27, 0, 0),
 datetime.datetime(2014, 12, 28, 0, 0),
 datetime.datetime(2014, 12, 29, 0, 0),
 datetime.datetime(2014, 12, 30, 0, 0)]

In [82]:
[min_date + timedelta(days = i) for i in range((max_date - min_date).days + 1)]

[datetime.datetime(2014, 1, 1, 0, 0),
 datetime.datetime(2014, 1, 2, 0, 0),
 datetime.datetime(2014, 1, 3, 0, 0),
 datetime.datetime(2014, 1, 4, 0, 0),
 datetime.datetime(2014, 1, 5, 0, 0),
 datetime.datetime(2014, 1, 6, 0, 0),
 datetime.datetime(2014, 1, 7, 0, 0),
 datetime.datetime(2014, 1, 8, 0, 0),
 datetime.datetime(2014, 1, 9, 0, 0),
 datetime.datetime(2014, 1, 10, 0, 0),
 datetime.datetime(2014, 1, 11, 0, 0),
 datetime.datetime(2014, 1, 12, 0, 0),
 datetime.datetime(2014, 1, 13, 0, 0),
 datetime.datetime(2014, 1, 14, 0, 0),
 datetime.datetime(2014, 1, 15, 0, 0),
 datetime.datetime(2014, 1, 16, 0, 0),
 datetime.datetime(2014, 1, 17, 0, 0),
 datetime.datetime(2014, 1, 18, 0, 0),
 datetime.datetime(2014, 1, 19, 0, 0),
 datetime.datetime(2014, 1, 20, 0, 0),
 datetime.datetime(2014, 1, 21, 0, 0),
 datetime.datetime(2014, 1, 22, 0, 0),
 datetime.datetime(2014, 1, 23, 0, 0),
 datetime.datetime(2014, 1, 24, 0, 0),
 datetime.datetime(2014, 1, 25, 0, 0),
 datetime.datetime(2014, 1, 26, 0, 0),
 datetime.datetime(2014, 1, 27, 0, 0),
 datetime.datetime(2014, 1, 28, 0, 0),
 datetime.datetime(2014, 1, 29, 0, 0),
 datetime.datetime(2014, 1, 30, 0, 0),
 datetime.datetime(2014, 1, 31, 0, 0),
 datetime.datetime(2014, 2, 1, 0, 0),
 datetime.datetime(2014, 2, 2, 0, 0),
 datetime.datetime(2014, 2, 3, 0, 0),
 datetime.datetime(2014, 2, 4, 0, 0),
 datetime.datetime(2014, 2, 5, 0, 0),
 datetime.datetime(2014, 2, 6, 0, 0),
 datetime.datetime(2014, 2, 7, 0, 0),
 datetime.datetime(2014, 2, 8, 0, 0),
 datetime.datetime(2014, 2, 9, 0, 0),
 datetime.datetime(2014, 2, 10, 0, 0),
 datetime.datetime(2014, 2, 11, 0, 0),
 datetime.datetime(2014, 2, 12, 0, 0),
 datetime.datetime(2014, 2, 13, 0, 0),
 datetime.datetime(2014, 2, 14, 0, 0),
 datetime.datetime(2014, 2, 15, 0, 0),
 datetime.datetime(2014, 2, 16, 0, 0),
 datetime.datetime(2014, 2, 17, 0, 0),
 datetime.datetime(2014, 2, 18, 0, 0),
 datetime.datetime(2014, 2, 19, 0, 0),
 datetime.datetime(2014, 2, 20, 0, 0),
 datetime.datetime(2014, 2, 21, 0, 0),
 datetime.datetime(2014, 2, 22, 0, 0),
 datetime.datetime(2014, 2, 23, 0, 0),
 datetime.datetime(2014, 2, 24, 0, 0),
 datetime.datetime(2014, 2, 25, 0, 0),
 datetime.datetime(2014, 2, 26, 0, 0),
 datetime.datetime(2014, 2, 27, 0, 0),
 datetime.datetime(2014, 2, 28, 0, 0),
 datetime.datetime(2014, 3, 1, 0, 0),
 datetime.datetime(2014, 3, 2, 0, 0),
 datetime.datetime(2014, 3, 3, 0, 0),
 datetime.datetime(2014, 3, 4, 0, 0),
 datetime.datetime(2014, 3, 5, 0, 0),
 datetime.datetime(2014, 3, 6, 0, 0),
 datetime.datetime(2014, 3, 7, 0, 0),
 datetime.datetime(2014, 3, 8, 0, 0),
 datetime.datetime(2014, 3, 9, 0, 0),
 datetime.datetime(2014, 3, 10, 0, 0),
 datetime.datetime(2014, 3, 11, 0, 0),
 datetime.datetime(2014, 3, 12, 0, 0),
 datetime.datetime(2014, 3, 13, 0, 0),
 datetime.datetime(2014, 3, 14, 0, 0),
 datetime.datetime(2014, 3, 15, 0, 0),
 datetime.datetime(2014, 3, 16, 0, 0),
 datetime.datetime(2014, 3, 17, 0, 0),
 datetime.datetime(2014, 3, 18, 0, 0),
 datetime.datetime(2014, 3, 19, 0, 0),
 datetime.datetime(2014, 3, 20, 0, 0),
 datetime.datetime(2014, 3, 21, 0, 0),
 datetime.datetime(2014, 3, 22, 0, 0),
 datetime.datetime(2014, 3, 23, 0, 0),
 datetime.datetime(2014, 3, 24, 0, 0),
 datetime.datetime(2014, 3, 25, 0, 0),
 datetime.datetime(2014, 3, 26, 0, 0),
 datetime.datetime(2014, 3, 27, 0, 0),
 datetime.datetime(2014, 3, 28, 0, 0),
 datetime.datetime(2014, 3, 29, 0, 0),
 datetime.datetime(2014, 3, 30, 0, 0),
 datetime.datetime(2014, 3, 31, 0, 0),
 datetime.datetime(2014, 4, 1, 0, 0),
 datetime.datetime(2014, 4, 2, 0, 0),
 datetime.datetime(2014, 4, 3, 0, 0),
 datetime.datetime(2014, 4, 4, 0, 0),
 datetime.datetime(2014, 4, 5, 0, 0),
 datetime.datetime(2014, 4, 6, 0, 0),
 datetime.datetime(2014, 4, 7, 0, 0),
 datetime.datetime(2014, 4, 8, 0, 0),
 datetime.datetime(2014, 4, 9, 0, 0),
 datetime.datetime(2014, 4, 10, 0, 0),
 datetime.datetime(2014, 4, 11, 0, 0),
 datetime.datetime(2014, 4, 12, 0, 0),
 datetime.datetime(2014, 4, 13, 0, 0),
 datetime.datetime(2014, 4, 14, 0, 0),
 datetime.datetime(2014, 4, 15, 0, 0),
 datetime.datetime(2014, 4, 16, 0, 0),
 datetime.datetime(2014, 4, 17, 0, 0),
 datetime.datetime(2014, 4, 18, 0, 0),
 datetime.datetime(2014, 4, 19, 0, 0),
 datetime.datetime(2014, 4, 20, 0, 0),
 datetime.datetime(2014, 4, 21, 0, 0),
 datetime.datetime(2014, 4, 22, 0, 0),
 datetime.datetime(2014, 4, 23, 0, 0),
 datetime.datetime(2014, 4, 24, 0, 0),
 datetime.datetime(2014, 4, 25, 0, 0),
 datetime.datetime(2014, 4, 26, 0, 0),
 datetime.datetime(2014, 4, 27, 0, 0),
 datetime.datetime(2014, 4, 28, 0, 0),
 datetime.datetime(2014, 4, 29, 0, 0),
 datetime.datetime(2014, 4, 30, 0, 0),
 datetime.datetime(2014, 5, 1, 0, 0),
 datetime.datetime(2014, 5, 2, 0, 0),
 datetime.datetime(2014, 5, 3, 0, 0),
 datetime.datetime(2014, 5, 4, 0, 0),
 datetime.datetime(2014, 5, 5, 0, 0),
 datetime.datetime(2014, 5, 6, 0, 0),
 datetime.datetime(2014, 5, 7, 0, 0),
 datetime.datetime(2014, 5, 8, 0, 0),
 datetime.datetime(2014, 5, 9, 0, 0),
 datetime.datetime(2014, 5, 10, 0, 0),
 datetime.datetime(2014, 5, 11, 0, 0),
 datetime.datetime(2014, 5, 12, 0, 0),
 datetime.datetime(2014, 5, 13, 0, 0),
 datetime.datetime(2014, 5, 14, 0, 0),
 datetime.datetime(2014, 5, 15, 0, 0),
 datetime.datetime(2014, 5, 16, 0, 0),
 datetime.datetime(2014, 5, 17, 0, 0),
 datetime.datetime(2014, 5, 18, 0, 0),
 datetime.datetime(2014, 5, 19, 0, 0),
 datetime.datetime(2014, 5, 20, 0, 0),
 datetime.datetime(2014, 5, 21, 0, 0),
 datetime.datetime(2014, 5, 22, 0, 0),
 datetime.datetime(2014, 5, 23, 0, 0),
 datetime.datetime(2014, 5, 24, 0, 0),
 datetime.datetime(2014, 5, 25, 0, 0),
 datetime.datetime(2014, 5, 26, 0, 0),
 datetime.datetime(2014, 5, 27, 0, 0),
 datetime.datetime(2014, 5, 28, 0, 0),
 datetime.datetime(2014, 5, 29, 0, 0),
 datetime.datetime(2014, 5, 30, 0, 0),
 datetime.datetime(2014, 5, 31, 0, 0),
 datetime.datetime(2014, 6, 1, 0, 0),
 datetime.datetime(2014, 6, 2, 0, 0),
 datetime.datetime(2014, 6, 3, 0, 0),
 datetime.datetime(2014, 6, 4, 0, 0),
 datetime.datetime(2014, 6, 5, 0, 0),
 datetime.datetime(2014, 6, 6, 0, 0),
 datetime.datetime(2014, 6, 7, 0, 0),
 datetime.datetime(2014, 6, 8, 0, 0),
 datetime.datetime(2014, 6, 9, 0, 0),
 datetime.datetime(2014, 6, 10, 0, 0),
 datetime.datetime(2014, 6, 11, 0, 0),
 datetime.datetime(2014, 6, 12, 0, 0),
 datetime.datetime(2014, 6, 13, 0, 0),
 datetime.datetime(2014, 6, 14, 0, 0),
 datetime.datetime(2014, 6, 15, 0, 0),
 datetime.datetime(2014, 6, 16, 0, 0),
 datetime.datetime(2014, 6, 17, 0, 0),
 datetime.datetime(2014, 6, 18, 0, 0),
 datetime.datetime(2014, 6, 19, 0, 0),
 datetime.datetime(2014, 6, 20, 0, 0),
 datetime.datetime(2014, 6, 21, 0, 0),
 datetime.datetime(2014, 6, 22, 0, 0),
 datetime.datetime(2014, 6, 23, 0, 0),
 datetime.datetime(2014, 6, 24, 0, 0),
 datetime.datetime(2014, 6, 25, 0, 0),
 datetime.datetime(2014, 6, 26, 0, 0),
 datetime.datetime(2014, 6, 27, 0, 0),
 datetime.datetime(2014, 6, 28, 0, 0),
 datetime.datetime(2014, 6, 29, 0, 0),
 datetime.datetime(2014, 6, 30, 0, 0),
 datetime.datetime(2014, 7, 1, 0, 0),
 datetime.datetime(2014, 7, 2, 0, 0),
 datetime.datetime(2014, 7, 3, 0, 0),
 datetime.datetime(2014, 7, 4, 0, 0),
 datetime.datetime(2014, 7, 5, 0, 0),
 datetime.datetime(2014, 7, 6, 0, 0),
 datetime.datetime(2014, 7, 7, 0, 0),
 datetime.datetime(2014, 7, 8, 0, 0),
 datetime.datetime(2014, 7, 9, 0, 0),
 datetime.datetime(2014, 7, 10, 0, 0),
 datetime.datetime(2014, 7, 11, 0, 0),
 datetime.datetime(2014, 7, 12, 0, 0),
 datetime.datetime(2014, 7, 13, 0, 0),
 datetime.datetime(2014, 7, 14, 0, 0),
 datetime.datetime(2014, 7, 15, 0, 0),
 datetime.datetime(2014, 7, 16, 0, 0),
 datetime.datetime(2014, 7, 17, 0, 0),
 datetime.datetime(2014, 7, 18, 0, 0),
 datetime.datetime(2014, 7, 19, 0, 0),
 datetime.datetime(2014, 7, 20, 0, 0),
 datetime.datetime(2014, 7, 21, 0, 0),
 datetime.datetime(2014, 7, 22, 0, 0),
 datetime.datetime(2014, 7, 23, 0, 0),
 datetime.datetime(2014, 7, 24, 0, 0),
 datetime.datetime(2014, 7, 25, 0, 0),
 datetime.datetime(2014, 7, 26, 0, 0),
 datetime.datetime(2014, 7, 27, 0, 0),
 datetime.datetime(2014, 7, 28, 0, 0),
 datetime.datetime(2014, 7, 29, 0, 0),
 datetime.datetime(2014, 7, 30, 0, 0),
 datetime.datetime(2014, 7, 31, 0, 0),
 datetime.datetime(2014, 8, 1, 0, 0),
 datetime.datetime(2014, 8, 2, 0, 0),
 datetime.datetime(2014, 8, 3, 0, 0),
 datetime.datetime(2014, 8, 4, 0, 0),
 datetime.datetime(2014, 8, 5, 0, 0),
 datetime.datetime(2014, 8, 6, 0, 0),
 datetime.datetime(2014, 8, 7, 0, 0),
 datetime.datetime(2014, 8, 8, 0, 0),
 datetime.datetime(2014, 8, 9, 0, 0),
 datetime.datetime(2014, 8, 10, 0, 0),
 datetime.datetime(2014, 8, 11, 0, 0),
 datetime.datetime(2014, 8, 12, 0, 0),
 datetime.datetime(2014, 8, 13, 0, 0),
 datetime.datetime(2014, 8, 14, 0, 0),
 datetime.datetime(2014, 8, 15, 0, 0),
 datetime.datetime(2014, 8, 16, 0, 0),
 datetime.datetime(2014, 8, 17, 0, 0),
 datetime.datetime(2014, 8, 18, 0, 0),
 datetime.datetime(2014, 8, 19, 0, 0),
 datetime.datetime(2014, 8, 20, 0, 0),
 datetime.datetime(2014, 8, 21, 0, 0),
 datetime.datetime(2014, 8, 22, 0, 0),
 datetime.datetime(2014, 8, 23, 0, 0),
 datetime.datetime(2014, 8, 24, 0, 0),
 datetime.datetime(2014, 8, 25, 0, 0),
 datetime.datetime(2014, 8, 26, 0, 0),
 datetime.datetime(2014, 8, 27, 0, 0),
 datetime.datetime(2014, 8, 28, 0, 0),
 datetime.datetime(2014, 8, 29, 0, 0),
 datetime.datetime(2014, 8, 30, 0, 0),
 datetime.datetime(2014, 8, 31, 0, 0),
 datetime.datetime(2014, 9, 1, 0, 0),
 datetime.datetime(2014, 9, 2, 0, 0),
 datetime.datetime(2014, 9, 3, 0, 0),
 datetime.datetime(2014, 9, 4, 0, 0),
 datetime.datetime(2014, 9, 5, 0, 0),
 datetime.datetime(2014, 9, 6, 0, 0),
 datetime.datetime(2014, 9, 7, 0, 0),
 datetime.datetime(2014, 9, 8, 0, 0),
 datetime.datetime(2014, 9, 9, 0, 0),
 datetime.datetime(2014, 9, 10, 0, 0),
 datetime.datetime(2014, 9, 11, 0, 0),
 datetime.datetime(2014, 9, 12, 0, 0),
 datetime.datetime(2014, 9, 13, 0, 0),
 datetime.datetime(2014, 9, 14, 0, 0),
 datetime.datetime(2014, 9, 15, 0, 0),
 datetime.datetime(2014, 9, 16, 0, 0),
 datetime.datetime(2014, 9, 17, 0, 0),
 datetime.datetime(2014, 9, 18, 0, 0),
 datetime.datetime(2014, 9, 19, 0, 0),
 datetime.datetime(2014, 9, 20, 0, 0),
 datetime.datetime(2014, 9, 21, 0, 0),
 datetime.datetime(2014, 9, 22, 0, 0),
 datetime.datetime(2014, 9, 23, 0, 0),
 datetime.datetime(2014, 9, 24, 0, 0),
 datetime.datetime(2014, 9, 25, 0, 0),
 datetime.datetime(2014, 9, 26, 0, 0),
 datetime.datetime(2014, 9, 27, 0, 0),
 datetime.datetime(2014, 9, 28, 0, 0),
 datetime.datetime(2014, 9, 29, 0, 0),
 datetime.datetime(2014, 9, 30, 0, 0),
 datetime.datetime(2014, 10, 1, 0, 0),
 datetime.datetime(2014, 10, 2, 0, 0),
 datetime.datetime(2014, 10, 3, 0, 0),
 datetime.datetime(2014, 10, 4, 0, 0),
 datetime.datetime(2014, 10, 5, 0, 0),
 datetime.datetime(2014, 10, 6, 0, 0),
 datetime.datetime(2014, 10, 7, 0, 0),
 datetime.datetime(2014, 10, 8, 0, 0),
 datetime.datetime(2014, 10, 9, 0, 0),
 datetime.datetime(2014, 10, 10, 0, 0),
 datetime.datetime(2014, 10, 11, 0, 0),
 datetime.datetime(2014, 10, 12, 0, 0),
 datetime.datetime(2014, 10, 13, 0, 0),
 datetime.datetime(2014, 10, 14, 0, 0),
 datetime.datetime(2014, 10, 15, 0, 0),
 datetime.datetime(2014, 10, 16, 0, 0),
 datetime.datetime(2014, 10, 17, 0, 0),
 datetime.datetime(2014, 10, 18, 0, 0),
 datetime.datetime(2014, 10, 19, 0, 0),
 datetime.datetime(2014, 10, 20, 0, 0),
 datetime.datetime(2014, 10, 21, 0, 0),
 datetime.datetime(2014, 10, 22, 0, 0),
 datetime.datetime(2014, 10, 23, 0, 0),
 datetime.datetime(2014, 10, 24, 0, 0),
 datetime.datetime(2014, 10, 25, 0, 0),
 datetime.datetime(2014, 10, 26, 0, 0),
 datetime.datetime(2014, 10, 27, 0, 0),
 datetime.datetime(2014, 10, 28, 0, 0),
 datetime.datetime(2014, 10, 29, 0, 0),
 datetime.datetime(2014, 10, 30, 0, 0),
 datetime.datetime(2014, 10, 31, 0, 0),
 datetime.datetime(2014, 11, 1, 0, 0),
 datetime.datetime(2014, 11, 2, 0, 0),
 datetime.datetime(2014, 11, 3, 0, 0),
 datetime.datetime(2014, 11, 4, 0, 0),
 datetime.datetime(2014, 11, 5, 0, 0),
 datetime.datetime(2014, 11, 6, 0, 0),
 datetime.datetime(2014, 11, 7, 0, 0),
 datetime.datetime(2014, 11, 8, 0, 0),
 datetime.datetime(2014, 11, 9, 0, 0),
 datetime.datetime(2014, 11, 10, 0, 0),
 datetime.datetime(2014, 11, 11, 0, 0),
 datetime.datetime(2014, 11, 12, 0, 0),
 datetime.datetime(2014, 11, 13, 0, 0),
 datetime.datetime(2014, 11, 14, 0, 0),
 datetime.datetime(2014, 11, 15, 0, 0),
 datetime.datetime(2014, 11, 16, 0, 0),
 datetime.datetime(2014, 11, 17, 0, 0),
 datetime.datetime(2014, 11, 18, 0, 0),
 datetime.datetime(2014, 11, 19, 0, 0),
 datetime.datetime(2014, 11, 20, 0, 0),
 datetime.datetime(2014, 11, 21, 0, 0),
 datetime.datetime(2014, 11, 22, 0, 0),
 datetime.datetime(2014, 11, 23, 0, 0),
 datetime.datetime(2014, 11, 24, 0, 0),
 datetime.datetime(2014, 11, 25, 0, 0),
 datetime.datetime(2014, 11, 26, 0, 0),
 datetime.datetime(2014, 11, 27, 0, 0),
 datetime.datetime(2014, 11, 28, 0, 0),
 datetime.datetime(2014, 11, 29, 0, 0),
 datetime.datetime(2014, 11, 30, 0, 0),
 datetime.datetime(2014, 12, 1, 0, 0),
 datetime.datetime(2014, 12, 2, 0, 0),
 datetime.datetime(2014, 12, 3, 0, 0),
 datetime.datetime(2014, 12, 4, 0, 0),
 datetime.datetime(2014, 12, 5, 0, 0),
 datetime.datetime(2014, 12, 6, 0, 0),
 datetime.datetime(2014, 12, 7, 0, 0),
 datetime.datetime(2014, 12, 8, 0, 0),
 datetime.datetime(2014, 12, 9, 0, 0),
 datetime.datetime(2014, 12, 10, 0, 0),
 datetime.datetime(2014, 12, 11, 0, 0),
 datetime.datetime(2014, 12, 12, 0, 0),
 datetime.datetime(2014, 12, 13, 0, 0),
 datetime.datetime(2014, 12, 14, 0, 0),
 datetime.datetime(2014, 12, 15, 0, 0),
 datetime.datetime(2014, 12, 16, 0, 0),
 datetime.datetime(2014, 12, 17, 0, 0),
 datetime.datetime(2014, 12, 18, 0, 0),
 datetime.datetime(2014, 12, 19, 0, 0),
 datetime.datetime(2014, 12, 20, 0, 0),
 datetime.datetime(2014, 12, 21, 0, 0),
 datetime.datetime(2014, 12, 22, 0, 0),
 datetime.datetime(2014, 12, 23, 0, 0),
 datetime.datetime(2014, 12, 24, 0, 0),
 datetime.datetime(2014, 12, 25, 0, 0),
 datetime.datetime(2014, 12, 26, 0, 0),
 datetime.datetime(2014, 12, 27, 0, 0),
 datetime.datetime(2014, 12, 28, 0, 0),
 datetime.datetime(2014, 12, 29, 0, 0),
 datetime.datetime(2014, 12, 30, 0, 0),
 datetime.datetime(2014, 12, 31, 0, 0)]

In [83]:
new_index = [min_date + timedelta(days = i) for i in range((max_date - min_date).days + 1)]

In [84]:
new_index

[datetime.datetime(2014, 1, 1, 0, 0),
 datetime.datetime(2014, 1, 2, 0, 0),
 datetime.datetime(2014, 1, 3, 0, 0),
 datetime.datetime(2014, 1, 4, 0, 0),
 datetime.datetime(2014, 1, 5, 0, 0),
 datetime.datetime(2014, 1, 6, 0, 0),
 datetime.datetime(2014, 1, 7, 0, 0),
 datetime.datetime(2014, 1, 8, 0, 0),
 datetime.datetime(2014, 1, 9, 0, 0),
 datetime.datetime(2014, 1, 10, 0, 0),
 datetime.datetime(2014, 1, 11, 0, 0),
 datetime.datetime(2014, 1, 12, 0, 0),
 datetime.datetime(2014, 1, 13, 0, 0),
 datetime.datetime(2014, 1, 14, 0, 0),
 datetime.datetime(2014, 1, 15, 0, 0),
 datetime.datetime(2014, 1, 16, 0, 0),
 datetime.datetime(2014, 1, 17, 0, 0),
 datetime.datetime(2014, 1, 18, 0, 0),
 datetime.datetime(2014, 1, 19, 0, 0),
 datetime.datetime(2014, 1, 20, 0, 0),
 datetime.datetime(2014, 1, 21, 0, 0),
 datetime.datetime(2014, 1, 22, 0, 0),
 datetime.datetime(2014, 1, 23, 0, 0),
 datetime.datetime(2014, 1, 24, 0, 0),
 datetime.datetime(2014, 1, 25, 0, 0),
 datetime.datetime(2014, 1, 26, 0, 0),
 datetime.datetime(2014, 1, 27, 0, 0),
 datetime.datetime(2014, 1, 28, 0, 0),
 datetime.datetime(2014, 1, 29, 0, 0),
 datetime.datetime(2014, 1, 30, 0, 0),
 datetime.datetime(2014, 1, 31, 0, 0),
 datetime.datetime(2014, 2, 1, 0, 0),
 datetime.datetime(2014, 2, 2, 0, 0),
 datetime.datetime(2014, 2, 3, 0, 0),
 datetime.datetime(2014, 2, 4, 0, 0),
 datetime.datetime(2014, 2, 5, 0, 0),
 datetime.datetime(2014, 2, 6, 0, 0),
 datetime.datetime(2014, 2, 7, 0, 0),
 datetime.datetime(2014, 2, 8, 0, 0),
 datetime.datetime(2014, 2, 9, 0, 0),
 datetime.datetime(2014, 2, 10, 0, 0),
 datetime.datetime(2014, 2, 11, 0, 0),
 datetime.datetime(2014, 2, 12, 0, 0),
 datetime.datetime(2014, 2, 13, 0, 0),
 datetime.datetime(2014, 2, 14, 0, 0),
 datetime.datetime(2014, 2, 15, 0, 0),
 datetime.datetime(2014, 2, 16, 0, 0),
 datetime.datetime(2014, 2, 17, 0, 0),
 datetime.datetime(2014, 2, 18, 0, 0),
 datetime.datetime(2014, 2, 19, 0, 0),
 datetime.datetime(2014, 2, 20, 0, 0),
 datetime.datetime(2014, 2, 21, 0, 0),
 datetime.datetime(2014, 2, 22, 0, 0),
 datetime.datetime(2014, 2, 23, 0, 0),
 datetime.datetime(2014, 2, 24, 0, 0),
 datetime.datetime(2014, 2, 25, 0, 0),
 datetime.datetime(2014, 2, 26, 0, 0),
 datetime.datetime(2014, 2, 27, 0, 0),
 datetime.datetime(2014, 2, 28, 0, 0),
 datetime.datetime(2014, 3, 1, 0, 0),
 datetime.datetime(2014, 3, 2, 0, 0),
 datetime.datetime(2014, 3, 3, 0, 0),
 datetime.datetime(2014, 3, 4, 0, 0),
 datetime.datetime(2014, 3, 5, 0, 0),
 datetime.datetime(2014, 3, 6, 0, 0),
 datetime.datetime(2014, 3, 7, 0, 0),
 datetime.datetime(2014, 3, 8, 0, 0),
 datetime.datetime(2014, 3, 9, 0, 0),
 datetime.datetime(2014, 3, 10, 0, 0),
 datetime.datetime(2014, 3, 11, 0, 0),
 datetime.datetime(2014, 3, 12, 0, 0),
 datetime.datetime(2014, 3, 13, 0, 0),
 datetime.datetime(2014, 3, 14, 0, 0),
 datetime.datetime(2014, 3, 15, 0, 0),
 datetime.datetime(2014, 3, 16, 0, 0),
 datetime.datetime(2014, 3, 17, 0, 0),
 datetime.datetime(2014, 3, 18, 0, 0),
 datetime.datetime(2014, 3, 19, 0, 0),
 datetime.datetime(2014, 3, 20, 0, 0),
 datetime.datetime(2014, 3, 21, 0, 0),
 datetime.datetime(2014, 3, 22, 0, 0),
 datetime.datetime(2014, 3, 23, 0, 0),
 datetime.datetime(2014, 3, 24, 0, 0),
 datetime.datetime(2014, 3, 25, 0, 0),
 datetime.datetime(2014, 3, 26, 0, 0),
 datetime.datetime(2014, 3, 27, 0, 0),
 datetime.datetime(2014, 3, 28, 0, 0),
 datetime.datetime(2014, 3, 29, 0, 0),
 datetime.datetime(2014, 3, 30, 0, 0),
 datetime.datetime(2014, 3, 31, 0, 0),
 datetime.datetime(2014, 4, 1, 0, 0),
 datetime.datetime(2014, 4, 2, 0, 0),
 datetime.datetime(2014, 4, 3, 0, 0),
 datetime.datetime(2014, 4, 4, 0, 0),
 datetime.datetime(2014, 4, 5, 0, 0),
 datetime.datetime(2014, 4, 6, 0, 0),
 datetime.datetime(2014, 4, 7, 0, 0),
 datetime.datetime(2014, 4, 8, 0, 0),
 datetime.datetime(2014, 4, 9, 0, 0),
 datetime.datetime(2014, 4, 10, 0, 0),
 datetime.datetime(2014, 4, 11, 0, 0),
 datetime.datetime(2014, 4, 12, 0, 0),
 datetime.datetime(2014, 4, 13, 0, 0),
 datetime.datetime(2014, 4, 14, 0, 0),
 datetime.datetime(2014, 4, 15, 0, 0),
 datetime.datetime(2014, 4, 16, 0, 0),
 datetime.datetime(2014, 4, 17, 0, 0),
 datetime.datetime(2014, 4, 18, 0, 0),
 datetime.datetime(2014, 4, 19, 0, 0),
 datetime.datetime(2014, 4, 20, 0, 0),
 datetime.datetime(2014, 4, 21, 0, 0),
 datetime.datetime(2014, 4, 22, 0, 0),
 datetime.datetime(2014, 4, 23, 0, 0),
 datetime.datetime(2014, 4, 24, 0, 0),
 datetime.datetime(2014, 4, 25, 0, 0),
 datetime.datetime(2014, 4, 26, 0, 0),
 datetime.datetime(2014, 4, 27, 0, 0),
 datetime.datetime(2014, 4, 28, 0, 0),
 datetime.datetime(2014, 4, 29, 0, 0),
 datetime.datetime(2014, 4, 30, 0, 0),
 datetime.datetime(2014, 5, 1, 0, 0),
 datetime.datetime(2014, 5, 2, 0, 0),
 datetime.datetime(2014, 5, 3, 0, 0),
 datetime.datetime(2014, 5, 4, 0, 0),
 datetime.datetime(2014, 5, 5, 0, 0),
 datetime.datetime(2014, 5, 6, 0, 0),
 datetime.datetime(2014, 5, 7, 0, 0),
 datetime.datetime(2014, 5, 8, 0, 0),
 datetime.datetime(2014, 5, 9, 0, 0),
 datetime.datetime(2014, 5, 10, 0, 0),
 datetime.datetime(2014, 5, 11, 0, 0),
 datetime.datetime(2014, 5, 12, 0, 0),
 datetime.datetime(2014, 5, 13, 0, 0),
 datetime.datetime(2014, 5, 14, 0, 0),
 datetime.datetime(2014, 5, 15, 0, 0),
 datetime.datetime(2014, 5, 16, 0, 0),
 datetime.datetime(2014, 5, 17, 0, 0),
 datetime.datetime(2014, 5, 18, 0, 0),
 datetime.datetime(2014, 5, 19, 0, 0),
 datetime.datetime(2014, 5, 20, 0, 0),
 datetime.datetime(2014, 5, 21, 0, 0),
 datetime.datetime(2014, 5, 22, 0, 0),
 datetime.datetime(2014, 5, 23, 0, 0),
 datetime.datetime(2014, 5, 24, 0, 0),
 datetime.datetime(2014, 5, 25, 0, 0),
 datetime.datetime(2014, 5, 26, 0, 0),
 datetime.datetime(2014, 5, 27, 0, 0),
 datetime.datetime(2014, 5, 28, 0, 0),
 datetime.datetime(2014, 5, 29, 0, 0),
 datetime.datetime(2014, 5, 30, 0, 0),
 datetime.datetime(2014, 5, 31, 0, 0),
 datetime.datetime(2014, 6, 1, 0, 0),
 datetime.datetime(2014, 6, 2, 0, 0),
 datetime.datetime(2014, 6, 3, 0, 0),
 datetime.datetime(2014, 6, 4, 0, 0),
 datetime.datetime(2014, 6, 5, 0, 0),
 datetime.datetime(2014, 6, 6, 0, 0),
 datetime.datetime(2014, 6, 7, 0, 0),
 datetime.datetime(2014, 6, 8, 0, 0),
 datetime.datetime(2014, 6, 9, 0, 0),
 datetime.datetime(2014, 6, 10, 0, 0),
 datetime.datetime(2014, 6, 11, 0, 0),
 datetime.datetime(2014, 6, 12, 0, 0),
 datetime.datetime(2014, 6, 13, 0, 0),
 datetime.datetime(2014, 6, 14, 0, 0),
 datetime.datetime(2014, 6, 15, 0, 0),
 datetime.datetime(2014, 6, 16, 0, 0),
 datetime.datetime(2014, 6, 17, 0, 0),
 datetime.datetime(2014, 6, 18, 0, 0),
 datetime.datetime(2014, 6, 19, 0, 0),
 datetime.datetime(2014, 6, 20, 0, 0),
 datetime.datetime(2014, 6, 21, 0, 0),
 datetime.datetime(2014, 6, 22, 0, 0),
 datetime.datetime(2014, 6, 23, 0, 0),
 datetime.datetime(2014, 6, 24, 0, 0),
 datetime.datetime(2014, 6, 25, 0, 0),
 datetime.datetime(2014, 6, 26, 0, 0),
 datetime.datetime(2014, 6, 27, 0, 0),
 datetime.datetime(2014, 6, 28, 0, 0),
 datetime.datetime(2014, 6, 29, 0, 0),
 datetime.datetime(2014, 6, 30, 0, 0),
 datetime.datetime(2014, 7, 1, 0, 0),
 datetime.datetime(2014, 7, 2, 0, 0),
 datetime.datetime(2014, 7, 3, 0, 0),
 datetime.datetime(2014, 7, 4, 0, 0),
 datetime.datetime(2014, 7, 5, 0, 0),
 datetime.datetime(2014, 7, 6, 0, 0),
 datetime.datetime(2014, 7, 7, 0, 0),
 datetime.datetime(2014, 7, 8, 0, 0),
 datetime.datetime(2014, 7, 9, 0, 0),
 datetime.datetime(2014, 7, 10, 0, 0),
 datetime.datetime(2014, 7, 11, 0, 0),
 datetime.datetime(2014, 7, 12, 0, 0),
 datetime.datetime(2014, 7, 13, 0, 0),
 datetime.datetime(2014, 7, 14, 0, 0),
 datetime.datetime(2014, 7, 15, 0, 0),
 datetime.datetime(2014, 7, 16, 0, 0),
 datetime.datetime(2014, 7, 17, 0, 0),
 datetime.datetime(2014, 7, 18, 0, 0),
 datetime.datetime(2014, 7, 19, 0, 0),
 datetime.datetime(2014, 7, 20, 0, 0),
 datetime.datetime(2014, 7, 21, 0, 0),
 datetime.datetime(2014, 7, 22, 0, 0),
 datetime.datetime(2014, 7, 23, 0, 0),
 datetime.datetime(2014, 7, 24, 0, 0),
 datetime.datetime(2014, 7, 25, 0, 0),
 datetime.datetime(2014, 7, 26, 0, 0),
 datetime.datetime(2014, 7, 27, 0, 0),
 datetime.datetime(2014, 7, 28, 0, 0),
 datetime.datetime(2014, 7, 29, 0, 0),
 datetime.datetime(2014, 7, 30, 0, 0),
 datetime.datetime(2014, 7, 31, 0, 0),
 datetime.datetime(2014, 8, 1, 0, 0),
 datetime.datetime(2014, 8, 2, 0, 0),
 datetime.datetime(2014, 8, 3, 0, 0),
 datetime.datetime(2014, 8, 4, 0, 0),
 datetime.datetime(2014, 8, 5, 0, 0),
 datetime.datetime(2014, 8, 6, 0, 0),
 datetime.datetime(2014, 8, 7, 0, 0),
 datetime.datetime(2014, 8, 8, 0, 0),
 datetime.datetime(2014, 8, 9, 0, 0),
 datetime.datetime(2014, 8, 10, 0, 0),
 datetime.datetime(2014, 8, 11, 0, 0),
 datetime.datetime(2014, 8, 12, 0, 0),
 datetime.datetime(2014, 8, 13, 0, 0),
 datetime.datetime(2014, 8, 14, 0, 0),
 datetime.datetime(2014, 8, 15, 0, 0),
 datetime.datetime(2014, 8, 16, 0, 0),
 datetime.datetime(2014, 8, 17, 0, 0),
 datetime.datetime(2014, 8, 18, 0, 0),
 datetime.datetime(2014, 8, 19, 0, 0),
 datetime.datetime(2014, 8, 20, 0, 0),
 datetime.datetime(2014, 8, 21, 0, 0),
 datetime.datetime(2014, 8, 22, 0, 0),
 datetime.datetime(2014, 8, 23, 0, 0),
 datetime.datetime(2014, 8, 24, 0, 0),
 datetime.datetime(2014, 8, 25, 0, 0),
 datetime.datetime(2014, 8, 26, 0, 0),
 datetime.datetime(2014, 8, 27, 0, 0),
 datetime.datetime(2014, 8, 28, 0, 0),
 datetime.datetime(2014, 8, 29, 0, 0),
 datetime.datetime(2014, 8, 30, 0, 0),
 datetime.datetime(2014, 8, 31, 0, 0),
 datetime.datetime(2014, 9, 1, 0, 0),
 datetime.datetime(2014, 9, 2, 0, 0),
 datetime.datetime(2014, 9, 3, 0, 0),
 datetime.datetime(2014, 9, 4, 0, 0),
 datetime.datetime(2014, 9, 5, 0, 0),
 datetime.datetime(2014, 9, 6, 0, 0),
 datetime.datetime(2014, 9, 7, 0, 0),
 datetime.datetime(2014, 9, 8, 0, 0),
 datetime.datetime(2014, 9, 9, 0, 0),
 datetime.datetime(2014, 9, 10, 0, 0),
 datetime.datetime(2014, 9, 11, 0, 0),
 datetime.datetime(2014, 9, 12, 0, 0),
 datetime.datetime(2014, 9, 13, 0, 0),
 datetime.datetime(2014, 9, 14, 0, 0),
 datetime.datetime(2014, 9, 15, 0, 0),
 datetime.datetime(2014, 9, 16, 0, 0),
 datetime.datetime(2014, 9, 17, 0, 0),
 datetime.datetime(2014, 9, 18, 0, 0),
 datetime.datetime(2014, 9, 19, 0, 0),
 datetime.datetime(2014, 9, 20, 0, 0),
 datetime.datetime(2014, 9, 21, 0, 0),
 datetime.datetime(2014, 9, 22, 0, 0),
 datetime.datetime(2014, 9, 23, 0, 0),
 datetime.datetime(2014, 9, 24, 0, 0),
 datetime.datetime(2014, 9, 25, 0, 0),
 datetime.datetime(2014, 9, 26, 0, 0),
 datetime.datetime(2014, 9, 27, 0, 0),
 datetime.datetime(2014, 9, 28, 0, 0),
 datetime.datetime(2014, 9, 29, 0, 0),
 datetime.datetime(2014, 9, 30, 0, 0),
 datetime.datetime(2014, 10, 1, 0, 0),
 datetime.datetime(2014, 10, 2, 0, 0),
 datetime.datetime(2014, 10, 3, 0, 0),
 datetime.datetime(2014, 10, 4, 0, 0),
 datetime.datetime(2014, 10, 5, 0, 0),
 datetime.datetime(2014, 10, 6, 0, 0),
 datetime.datetime(2014, 10, 7, 0, 0),
 datetime.datetime(2014, 10, 8, 0, 0),
 datetime.datetime(2014, 10, 9, 0, 0),
 datetime.datetime(2014, 10, 10, 0, 0),
 datetime.datetime(2014, 10, 11, 0, 0),
 datetime.datetime(2014, 10, 12, 0, 0),
 datetime.datetime(2014, 10, 13, 0, 0),
 datetime.datetime(2014, 10, 14, 0, 0),
 datetime.datetime(2014, 10, 15, 0, 0),
 datetime.datetime(2014, 10, 16, 0, 0),
 datetime.datetime(2014, 10, 17, 0, 0),
 datetime.datetime(2014, 10, 18, 0, 0),
 datetime.datetime(2014, 10, 19, 0, 0),
 datetime.datetime(2014, 10, 20, 0, 0),
 datetime.datetime(2014, 10, 21, 0, 0),
 datetime.datetime(2014, 10, 22, 0, 0),
 datetime.datetime(2014, 10, 23, 0, 0),
 datetime.datetime(2014, 10, 24, 0, 0),
 datetime.datetime(2014, 10, 25, 0, 0),
 datetime.datetime(2014, 10, 26, 0, 0),
 datetime.datetime(2014, 10, 27, 0, 0),
 datetime.datetime(2014, 10, 28, 0, 0),
 datetime.datetime(2014, 10, 29, 0, 0),
 datetime.datetime(2014, 10, 30, 0, 0),
 datetime.datetime(2014, 10, 31, 0, 0),
 datetime.datetime(2014, 11, 1, 0, 0),
 datetime.datetime(2014, 11, 2, 0, 0),
 datetime.datetime(2014, 11, 3, 0, 0),
 datetime.datetime(2014, 11, 4, 0, 0),
 datetime.datetime(2014, 11, 5, 0, 0),
 datetime.datetime(2014, 11, 6, 0, 0),
 datetime.datetime(2014, 11, 7, 0, 0),
 datetime.datetime(2014, 11, 8, 0, 0),
 datetime.datetime(2014, 11, 9, 0, 0),
 datetime.datetime(2014, 11, 10, 0, 0),
 datetime.datetime(2014, 11, 11, 0, 0),
 datetime.datetime(2014, 11, 12, 0, 0),
 datetime.datetime(2014, 11, 13, 0, 0),
 datetime.datetime(2014, 11, 14, 0, 0),
 datetime.datetime(2014, 11, 15, 0, 0),
 datetime.datetime(2014, 11, 16, 0, 0),
 datetime.datetime(2014, 11, 17, 0, 0),
 datetime.datetime(2014, 11, 18, 0, 0),
 datetime.datetime(2014, 11, 19, 0, 0),
 datetime.datetime(2014, 11, 20, 0, 0),
 datetime.datetime(2014, 11, 21, 0, 0),
 datetime.datetime(2014, 11, 22, 0, 0),
 datetime.datetime(2014, 11, 23, 0, 0),
 datetime.datetime(2014, 11, 24, 0, 0),
 datetime.datetime(2014, 11, 25, 0, 0),
 datetime.datetime(2014, 11, 26, 0, 0),
 datetime.datetime(2014, 11, 27, 0, 0),
 datetime.datetime(2014, 11, 28, 0, 0),
 datetime.datetime(2014, 11, 29, 0, 0),
 datetime.datetime(2014, 11, 30, 0, 0),
 datetime.datetime(2014, 12, 1, 0, 0),
 datetime.datetime(2014, 12, 2, 0, 0),
 datetime.datetime(2014, 12, 3, 0, 0),
 datetime.datetime(2014, 12, 4, 0, 0),
 datetime.datetime(2014, 12, 5, 0, 0),
 datetime.datetime(2014, 12, 6, 0, 0),
 datetime.datetime(2014, 12, 7, 0, 0),
 datetime.datetime(2014, 12, 8, 0, 0),
 datetime.datetime(2014, 12, 9, 0, 0),
 datetime.datetime(2014, 12, 10, 0, 0),
 datetime.datetime(2014, 12, 11, 0, 0),
 datetime.datetime(2014, 12, 12, 0, 0),
 datetime.datetime(2014, 12, 13, 0, 0),
 datetime.datetime(2014, 12, 14, 0, 0),
 datetime.datetime(2014, 12, 15, 0, 0),
 datetime.datetime(2014, 12, 16, 0, 0),
 datetime.datetime(2014, 12, 17, 0, 0),
 datetime.datetime(2014, 12, 18, 0, 0),
 datetime.datetime(2014, 12, 19, 0, 0),
 datetime.datetime(2014, 12, 20, 0, 0),
 datetime.datetime(2014, 12, 21, 0, 0),
 datetime.datetime(2014, 12, 22, 0, 0),
 datetime.datetime(2014, 12, 23, 0, 0),
 datetime.datetime(2014, 12, 24, 0, 0),
 datetime.datetime(2014, 12, 25, 0, 0),
 datetime.datetime(2014, 12, 26, 0, 0),
 datetime.datetime(2014, 12, 27, 0, 0),
 datetime.datetime(2014, 12, 28, 0, 0),
 datetime.datetime(2014, 12, 29, 0, 0),
 datetime.datetime(2014, 12, 30, 0, 0),
 datetime.datetime(2014, 12, 31, 0, 0)]

In [85]:
df_gsr_filled = df_gsr_aggregated.reindex(new_index)

In [86]:
df_gsr_filled

            event
date
2014-01-01      1
2014-01-02      1
2014-01-03      1
2014-01-04      1
2014-01-05      1
2014-01-06      1
2014-01-07      1
2014-01-08      1
2014-01-09      1
2014-01-10      1
2014-01-11      1
2014-01-12      1
2014-01-13      1
2014-01-14      1
2014-01-15      1
2014-01-16      1
2014-01-17      1
2014-01-18      1
2014-01-19      1
2014-01-20      1
2014-01-21      1
2014-01-22      1
2014-01-23      1
2014-01-24      1
2014-01-25      1
2014-01-26      1
2014-01-27      1
2014-01-28      1
2014-01-29      1
2014-01-30      1
...           ...
2014-12-02      1
2014-12-03      1
2014-12-04      1
2014-12-05      1
2014-12-06      1
2014-12-07      1
2014-12-08      1
2014-12-09      1
2014-12-10      1
2014-12-11      1
2014-12-12      1
2014-12-13      1
2014-12-14      1
2014-12-15      1
2014-12-16      1
2014-12-17      1
2014-12-18      1
2014-12-19      1
2014-12-20    NaN
2014-12-21    NaN
2014-12-22      1
2014-12-23    NaN
2014-12-24      1
2014-12-25    NaN
2014-12-26      1
2014-12-27    NaN
2014-12-28    NaN
2014-12-29      1
2014-12-30    NaN
2014-12-31      1

[365 rows x 1 columns]

In [87]:
df_gsr_filled.fillna(0)

            event
date
2014-01-01      1
2014-01-02      1
2014-01-03      1
2014-01-04      1
2014-01-05      1
2014-01-06      1
2014-01-07      1
2014-01-08      1
2014-01-09      1
2014-01-10      1
2014-01-11      1
2014-01-12      1
2014-01-13      1
2014-01-14      1
2014-01-15      1
2014-01-16      1
2014-01-17      1
2014-01-18      1
2014-01-19      1
2014-01-20      1
2014-01-21      1
2014-01-22      1
2014-01-23      1
2014-01-24      1
2014-01-25      1
2014-01-26      1
2014-01-27      1
2014-01-28      1
2014-01-29      1
2014-01-30      1
...           ...
2014-12-02      1
2014-12-03      1
2014-12-04      1
2014-12-05      1
2014-12-06      1
2014-12-07      1
2014-12-08      1
2014-12-09      1
2014-12-10      1
2014-12-11      1
2014-12-12      1
2014-12-13      1
2014-12-14      1
2014-12-15      1
2014-12-16      1
2014-12-17      1
2014-12-18      1
2014-12-19      1
2014-12-20      0
2014-12-21      0
2014-12-22      1
2014-12-23      0
2014-12-24      1
2014-12-25      0
2014-12-26      1
2014-12-27      0
2014-12-28      0
2014-12-29      1
2014-12-30      0
2014-12-31      1

[365 rows x 1 columns]

In [88]:
for index, row in df_gsr_filled.iterrows():
    print row['c1'], row['c2']

KeyError: 'c1'

In [89]:
for index, row in df_gsr_filled.iterrows():
    print index, row['event']

2014-01-01 00:00:00 1.0
2014-01-02 00:00:00 1.0
2014-01-03 00:00:00 1.0
2014-01-04 00:00:00 1.0
2014-01-05 00:00:00 1.0
2014-01-06 00:00:00 1.0
2014-01-07 00:00:00 1.0
2014-01-08 00:00:00 1.0
2014-01-09 00:00:00 1.0
2014-01-10 00:00:00 1.0
2014-01-11 00:00:00 1.0
2014-01-12 00:00:00 1.0
2014-01-13 00:00:00 1.0
2014-01-14 00:00:00 1.0
2014-01-15 00:00:00 1.0
2014-01-16 00:00:00 1.0
2014-01-17 00:00:00 1.0
2014-01-18 00:00:00 1.0
2014-01-19 00:00:00 1.0
2014-01-20 00:00:00 1.0
2014-01-21 00:00:00 1.0
2014-01-22 00:00:00 1.0
2014-01-23 00:00:00 1.0
2014-01-24 00:00:00 1.0
2014-01-25 00:00:00 1.0
2014-01-26 00:00:00 1.0
2014-01-27 00:00:00 1.0
2014-01-28 00:00:00 1.0
2014-01-29 00:00:00 1.0
2014-01-30 00:00:00 1.0
2014-01-31 00:00:00 1.0
2014-02-01 00:00:00 1.0
2014-02-02 00:00:00 1.0
2014-02-03 00:00:00 1.0
2014-02-04 00:00:00 1.0
2014-02-05 00:00:00 1.0
2014-02-06 00:00:00 1.0
2014-02-07 00:00:00 1.0
2014-02-08 00:00:00 1.0
2014-02-09 00:00:00 1.0
2014-02-10 00:00:00 1.0
2014-02-11 00:00:00 1.0
2014-02-12 00:00:00 1.0
2014-02-13 00:00:00 1.0
2014-02-14 00:00:00 1.0
2014-02-15 00:00:00 1.0
2014-02-16 00:00:00 1.0
2014-02-17 00:00:00 1.0
2014-02-18 00:00:00 1.0
2014-02-19 00:00:00 1.0
2014-02-20 00:00:00 1.0
2014-02-21 00:00:00 1.0
2014-02-22 00:00:00 1.0
2014-02-23 00:00:00 1.0
2014-02-24 00:00:00 1.0
2014-02-25 00:00:00 1.0
2014-02-26 00:00:00 1.0
2014-02-27 00:00:00 1.0
2014-02-28 00:00:00 1.0
2014-03-01 00:00:00 1.0
2014-03-02 00:00:00 1.0
2014-03-03 00:00:00 1.0
2014-03-04 00:00:00 1.0
2014-03-05 00:00:00 1.0
2014-03-06 00:00:00 1.0
2014-03-07 00:00:00 1.0
2014-03-08 00:00:00 1.0
2014-03-09 00:00:00 1.0
2014-03-10 00:00:00 1.0
2014-03-11 00:00:00 1.0
2014-03-12 00:00:00 1.0
2014-03-13 00:00:00 1.0
2014-03-14 00:00:00 1.0
2014-03-15 00:00:00 1.0
2014-03-16 00:00:00 1.0
2014-03-17 00:00:00 1.0
2014-03-18 00:00:00 1.0
2014-03-19 00:00:00 1.0
2014-03-20 00:00:00 1.0
2014-03-21 00:00:00 1.0
2014-03-22 00:00:00 1.0
2014-03-23 00:00:00 1.0
2014-03-24 00:00:00 1.0
2014-03-25 00:00:00 1.0
2014-03-26 00:00:00 1.0
2014-03-27 00:00:00 1.0
2014-03-28 00:00:00 1.0
2014-03-29 00:00:00 1.0
2014-03-30 00:00:00 1.0
2014-03-31 00:00:00 1.0
2014-04-01 00:00:00 1.0
2014-04-02 00:00:00 1.0
2014-04-03 00:00:00 1.0
2014-04-04 00:00:00 1.0
2014-04-05 00:00:00 1.0
2014-04-06 00:00:00 1.0
2014-04-07 00:00:00 1.0
2014-04-08 00:00:00 1.0
2014-04-09 00:00:00 1.0
2014-04-10 00:00:00 1.0
2014-04-11 00:00:00 1.0
2014-04-12 00:00:00 1.0
2014-04-13 00:00:00 1.0
2014-04-14 00:00:00 1.0
2014-04-15 00:00:00 1.0
2014-04-16 00:00:00 1.0
2014-04-17 00:00:00 1.0
2014-04-18 00:00:00 1.0
2014-04-19 00:00:00 1.0
2014-04-20 00:00:00 1.0
2014-04-21 00:00:00 1.0
2014-04-22 00:00:00 1.0
2014-04-23 00:00:00 1.0
2014-04-24 00:00:00 1.0
2014-04-25 00:00:00 1.0
2014-04-26 00:00:00 1.0
2014-04-27 00:00:00 1.0
2014-04-28 00:00:00 1.0
2014-04-29 00:00:00 1.0
2014-04-30 00:00:00 1.0
2014-05-01 00:00:00 1.0
2014-05-02 00:00:00 1.0
2014-05-03 00:00:00 1.0
2014-05-04 00:00:00 1.0
2014-05-05 00:00:00 1.0
2014-05-06 00:00:00 1.0
2014-05-07 00:00:00 1.0
2014-05-08 00:00:00 1.0
2014-05-09 00:00:00 1.0
2014-05-10 00:00:00 1.0
2014-05-11 00:00:00 nan
2014-05-12 00:00:00 1.0
2014-05-13 00:00:00 1.0
2014-05-14 00:00:00 1.0
2014-05-15 00:00:00 1.0
2014-05-16 00:00:00 1.0
2014-05-17 00:00:00 1.0
2014-05-18 00:00:00 1.0
2014-05-19 00:00:00 1.0
2014-05-20 00:00:00 1.0
2014-05-21 00:00:00 1.0
2014-05-22 00:00:00 1.0
2014-05-23 00:00:00 1.0
2014-05-24 00:00:00 1.0
2014-05-25 00:00:00 1.0
2014-05-26 00:00:00 1.0
2014-05-27 00:00:00 1.0
2014-05-28 00:00:00 1.0
2014-05-29 00:00:00 1.0
2014-05-30 00:00:00 1.0
2014-05-31 00:00:00 1.0
2014-06-01 00:00:00 1.0
2014-06-02 00:00:00 1.0
2014-06-03 00:00:00 1.0
2014-06-04 00:00:00 1.0
2014-06-05 00:00:00 1.0
2014-06-06 00:00:00 1.0
2014-06-07 00:00:00 1.0
2014-06-08 00:00:00 1.0
2014-06-09 00:00:00 1.0
2014-06-10 00:00:00 1.0
2014-06-11 00:00:00 1.0
2014-06-12 00:00:00 1.0
2014-06-13 00:00:00 1.0
2014-06-14 00:00:00 1.0
2014-06-15 00:00:00 1.0
2014-06-16 00:00:00 1.0
2014-06-17 00:00:00 1.0
2014-06-18 00:00:00 1.0
2014-06-19 00:00:00 1.0
2014-06-20 00:00:00 1.0
2014-06-21 00:00:00 1.0
2014-06-22 00:00:00 1.0
2014-06-23 00:00:00 1.0
2014-06-24 00:00:00 1.0
2014-06-25 00:00:00 1.0
2014-06-26 00:00:00 1.0
2014-06-27 00:00:00 1.0
2014-06-28 00:00:00 1.0
2014-06-29 00:00:00 1.0
2014-06-30 00:00:00 1.0
2014-07-01 00:00:00 1.0
2014-07-02 00:00:00 1.0
2014-07-03 00:00:00 1.0
2014-07-04 00:00:00 1.0
2014-07-05 00:00:00 1.0
2014-07-06 00:00:00 1.0
2014-07-07 00:00:00 1.0
2014-07-08 00:00:00 1.0
2014-07-09 00:00:00 1.0
2014-07-10 00:00:00 1.0
2014-07-11 00:00:00 nan
2014-07-12 00:00:00 1.0
2014-07-13 00:00:00 1.0
2014-07-14 00:00:00 1.0
2014-07-15 00:00:00 1.0
2014-07-16 00:00:00 1.0
2014-07-17 00:00:00 1.0
2014-07-18 00:00:00 1.0
2014-07-19 00:00:00 1.0
2014-07-20 00:00:00 1.0
2014-07-21 00:00:00 1.0
2014-07-22 00:00:00 1.0
2014-07-23 00:00:00 1.0
2014-07-24 00:00:00 1.0
2014-07-25 00:00:00 1.0
2014-07-26 00:00:00 nan
2014-07-27 00:00:00 1.0
2014-07-28 00:00:00 1.0
2014-07-29 00:00:00 1.0
2014-07-30 00:00:00 1.0
2014-07-31 00:00:00 1.0
2014-08-01 00:00:00 1.0
2014-08-02 00:00:00 1.0
2014-08-03 00:00:00 1.0
2014-08-04 00:00:00 1.0
2014-08-05 00:00:00 1.0
2014-08-06 00:00:00 1.0
2014-08-07 00:00:00 1.0
2014-08-08 00:00:00 1.0
2014-08-09 00:00:00 1.0
2014-08-10 00:00:00 1.0
2014-08-11 00:00:00 1.0
2014-08-12 00:00:00 1.0
2014-08-13 00:00:00 nan
2014-08-14 00:00:00 1.0
2014-08-15 00:00:00 nan
2014-08-16 00:00:00 nan
2014-08-17 00:00:00 nan
2014-08-18 00:00:00 nan
2014-08-19 00:00:00 1.0
2014-08-20 00:00:00 1.0
2014-08-21 00:00:00 1.0
2014-08-22 00:00:00 1.0
2014-08-23 00:00:00 nan
2014-08-24 00:00:00 1.0
2014-08-25 00:00:00 1.0
2014-08-26 00:00:00 1.0
2014-08-27 00:00:00 1.0
2014-08-28 00:00:00 1.0
2014-08-29 00:00:00 1.0
2014-08-30 00:00:00 1.0
2014-08-31 00:00:00 1.0
2014-09-01 00:00:00 1.0
2014-09-02 00:00:00 1.0
2014-09-03 00:00:00 1.0
2014-09-04 00:00:00 1.0
2014-09-05 00:00:00 1.0
2014-09-06 00:00:00 1.0
2014-09-07 00:00:00 1.0
2014-09-08 00:00:00 1.0
2014-09-09 00:00:00 1.0
2014-09-10 00:00:00 1.0
2014-09-11 00:00:00 1.0
2014-09-12 00:00:00 1.0
2014-09-13 00:00:00 1.0
2014-09-14 00:00:00 1.0
2014-09-15 00:00:00 1.0
2014-09-16 00:00:00 1.0
2014-09-17 00:00:00 1.0
2014-09-18 00:00:00 1.0
2014-09-19 00:00:00 1.0
2014-09-20 00:00:00 1.0
2014-09-21 00:00:00 1.0
2014-09-22 00:00:00 1.0
2014-09-23 00:00:00 1.0
2014-09-24 00:00:00 1.0
2014-09-25 00:00:00 1.0
2014-09-26 00:00:00 1.0
2014-09-27 00:00:00 1.0
2014-09-28 00:00:00 1.0
2014-09-29 00:00:00 1.0
2014-09-30 00:00:00 1.0
2014-10-01 00:00:00 1.0
2014-10-02 00:00:00 1.0
2014-10-03 00:00:00 1.0
2014-10-04 00:00:00 1.0
2014-10-05 00:00:00 1.0
2014-10-06 00:00:00 1.0
2014-10-07 00:00:00 1.0
2014-10-08 00:00:00 1.0
2014-10-09 00:00:00 1.0
2014-10-10 00:00:00 1.0
2014-10-11 00:00:00 1.0
2014-10-12 00:00:00 1.0
2014-10-13 00:00:00 1.0
2014-10-14 00:00:00 1.0
2014-10-15 00:00:00 1.0
2014-10-16 00:00:00 1.0
2014-10-17 00:00:00 1.0
2014-10-18 00:00:00 1.0
2014-10-19 00:00:00 1.0
2014-10-20 00:00:00 1.0
2014-10-21 00:00:00 1.0
2014-10-22 00:00:00 1.0
2014-10-23 00:00:00 1.0
2014-10-24 00:00:00 1.0
2014-10-25 00:00:00 1.0
2014-10-26 00:00:00 1.0
2014-10-27 00:00:00 1.0
2014-10-28 00:00:00 1.0
2014-10-29 00:00:00 1.0
2014-10-30 00:00:00 1.0
2014-10-31 00:00:00 nan
2014-11-01 00:00:00 1.0
2014-11-02 00:00:00 nan
2014-11-03 00:00:00 1.0
2014-11-04 00:00:00 1.0
2014-11-05 00:00:00 1.0
2014-11-06 00:00:00 1.0
2014-11-07 00:00:00 nan
2014-11-08 00:00:00 nan
2014-11-09 00:00:00 1.0
2014-11-10 00:00:00 1.0
2014-11-11 00:00:00 1.0
2014-11-12 00:00:00 1.0
2014-11-13 00:00:00 1.0
2014-11-14 00:00:00 nan
2014-11-15 00:00:00 1.0
2014-11-16 00:00:00 1.0
2014-11-17 00:00:00 1.0
2014-11-18 00:00:00 1.0
2014-11-19 00:00:00 1.0
2014-11-20 00:00:00 1.0
2014-11-21 00:00:00 1.0
2014-11-22 00:00:00 nan
2014-11-23 00:00:00 1.0
2014-11-24 00:00:00 1.0
2014-11-25 00:00:00 1.0
2014-11-26 00:00:00 1.0
2014-11-27 00:00:00 1.0
2014-11-28 00:00:00 1.0
2014-11-29 00:00:00 1.0
2014-11-30 00:00:00 1.0
2014-12-01 00:00:00 1.0
2014-12-02 00:00:00 1.0
2014-12-03 00:00:00 1.0
2014-12-04 00:00:00 1.0
2014-12-05 00:00:00 1.0
2014-12-06 00:00:00 1.0
2014-12-07 00:00:00 1.0
2014-12-08 00:00:00 1.0
2014-12-09 00:00:00 1.0
2014-12-10 00:00:00 1.0
2014-12-11 00:00:00 1.0
2014-12-12 00:00:00 1.0
2014-12-13 00:00:00 1.0
2014-12-14 00:00:00 1.0
2014-12-15 00:00:00 1.0
2014-12-16 00:00:00 1.0
2014-12-17 00:00:00 1.0
2014-12-18 00:00:00 1.0
2014-12-19 00:00:00 1.0
2014-12-20 00:00:00 nan
2014-12-21 00:00:00 nan
2014-12-22 00:00:00 1.0
2014-12-23 00:00:00 nan
2014-12-24 00:00:00 1.0
2014-12-25 00:00:00 nan
2014-12-26 00:00:00 1.0
2014-12-27 00:00:00 nan
2014-12-28 00:00:00 nan
2014-12-29 00:00:00 1.0
2014-12-30 00:00:00 nan
2014-12-31 00:00:00 1.0

In [90]:
last = df_gsr_filled.irow(0)

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: irow(i) is deprecated. Please use .iloc[i]
  if __name__ == '__main__':

In [91]:
last = df_gsr_filled.iloc(0)

In [92]:
last

In [93]:
last.name

'iloc'

In [94]:
last.axis

In [95]:
last.ndim

2

In [96]:
last = df_gsr_filled.iloc(1)

In [97]:
last.obj

            event
date
2014-01-01      1
2014-01-02      1
2014-01-03      1
2014-01-04      1
2014-01-05      1
2014-01-06      1
2014-01-07      1
2014-01-08      1
2014-01-09      1
2014-01-10      1
2014-01-11      1
2014-01-12      1
2014-01-13      1
2014-01-14      1
2014-01-15      1
2014-01-16      1
2014-01-17      1
2014-01-18      1
2014-01-19      1
2014-01-20      1
2014-01-21      1
2014-01-22      1
2014-01-23      1
2014-01-24      1
2014-01-25      1
2014-01-26      1
2014-01-27      1
2014-01-28      1
2014-01-29      1
2014-01-30      1
...           ...
2014-12-02      1
2014-12-03      1
2014-12-04      1
2014-12-05      1
2014-12-06      1
2014-12-07      1
2014-12-08      1
2014-12-09      1
2014-12-10      1
2014-12-11      1
2014-12-12      1
2014-12-13      1
2014-12-14      1
2014-12-15      1
2014-12-16      1
2014-12-17      1
2014-12-18      1
2014-12-19      1
2014-12-20    NaN
2014-12-21    NaN
2014-12-22      1
2014-12-23    NaN
2014-12-24      1
2014-12-25    NaN
2014-12-26      1
2014-12-27    NaN
2014-12-28    NaN
2014-12-29      1
2014-12-30    NaN
2014-12-31      1

[365 rows x 1 columns]

In [98]:
for index, row in df_gsr_filled.iterrows():
    print index +1

ValueError: Cannot add integral value to Timestamp without offset.

In [99]:
for index, row in df_gsr_filled.iterrows():
    print index + timedelta(days = 1)

2014-01-02 00:00:00
2014-01-03 00:00:00
2014-01-04 00:00:00
2014-01-05 00:00:00
2014-01-06 00:00:00
2014-01-07 00:00:00
2014-01-08 00:00:00
2014-01-09 00:00:00
2014-01-10 00:00:00
2014-01-11 00:00:00
2014-01-12 00:00:00
2014-01-13 00:00:00
2014-01-14 00:00:00
2014-01-15 00:00:00
2014-01-16 00:00:00
2014-01-17 00:00:00
2014-01-18 00:00:00
2014-01-19 00:00:00
2014-01-20 00:00:00
2014-01-21 00:00:00
2014-01-22 00:00:00
2014-01-23 00:00:00
2014-01-24 00:00:00
2014-01-25 00:00:00
2014-01-26 00:00:00
2014-01-27 00:00:00
2014-01-28 00:00:00
2014-01-29 00:00:00
2014-01-30 00:00:00
2014-01-31 00:00:00
2014-02-01 00:00:00
2014-02-02 00:00:00
2014-02-03 00:00:00
2014-02-04 00:00:00
2014-02-05 00:00:00
2014-02-06 00:00:00
2014-02-07 00:00:00
2014-02-08 00:00:00
2014-02-09 00:00:00
2014-02-10 00:00:00
2014-02-11 00:00:00
2014-02-12 00:00:00
2014-02-13 00:00:00
2014-02-14 00:00:00
2014-02-15 00:00:00
2014-02-16 00:00:00
2014-02-17 00:00:00
2014-02-18 00:00:00
2014-02-19 00:00:00
2014-02-20 00:00:00
2014-02-21 00:00:00
2014-02-22 00:00:00
2014-02-23 00:00:00
2014-02-24 00:00:00
2014-02-25 00:00:00
2014-02-26 00:00:00
2014-02-27 00:00:00
2014-02-28 00:00:00
2014-03-01 00:00:00
2014-03-02 00:00:00
2014-03-03 00:00:00
2014-03-04 00:00:00
2014-03-05 00:00:00
2014-03-06 00:00:00
2014-03-07 00:00:00
2014-03-08 00:00:00
2014-03-09 00:00:00
2014-03-10 00:00:00
2014-03-11 00:00:00
2014-03-12 00:00:00
2014-03-13 00:00:00
2014-03-14 00:00:00
2014-03-15 00:00:00
2014-03-16 00:00:00
2014-03-17 00:00:00
2014-03-18 00:00:00
2014-03-19 00:00:00
2014-03-20 00:00:00
2014-03-21 00:00:00
2014-03-22 00:00:00
2014-03-23 00:00:00
2014-03-24 00:00:00
2014-03-25 00:00:00
2014-03-26 00:00:00
2014-03-27 00:00:00
2014-03-28 00:00:00
2014-03-29 00:00:00
2014-03-30 00:00:00
2014-03-31 00:00:00
2014-04-01 00:00:00
2014-04-02 00:00:00
2014-04-03 00:00:00
2014-04-04 00:00:00
2014-04-05 00:00:00
2014-04-06 00:00:00
2014-04-07 00:00:00
2014-04-08 00:00:00
2014-04-09 00:00:00
2014-04-10 00:00:00
2014-04-11 00:00:00
2014-04-12 00:00:00
2014-04-13 00:00:00
2014-04-14 00:00:00
2014-04-15 00:00:00
2014-04-16 00:00:00
2014-04-17 00:00:00
2014-04-18 00:00:00
2014-04-19 00:00:00
2014-04-20 00:00:00
2014-04-21 00:00:00
2014-04-22 00:00:00
2014-04-23 00:00:00
2014-04-24 00:00:00
2014-04-25 00:00:00
2014-04-26 00:00:00
2014-04-27 00:00:00
2014-04-28 00:00:00
2014-04-29 00:00:00
2014-04-30 00:00:00
2014-05-01 00:00:00
2014-05-02 00:00:00
2014-05-03 00:00:00
2014-05-04 00:00:00
2014-05-05 00:00:00
2014-05-06 00:00:00
2014-05-07 00:00:00
2014-05-08 00:00:00
2014-05-09 00:00:00
2014-05-10 00:00:00
2014-05-11 00:00:00
2014-05-12 00:00:00
2014-05-13 00:00:00
2014-05-14 00:00:00
2014-05-15 00:00:00
2014-05-16 00:00:00
2014-05-17 00:00:00
2014-05-18 00:00:00
2014-05-19 00:00:00
2014-05-20 00:00:00
2014-05-21 00:00:00
2014-05-22 00:00:00
2014-05-23 00:00:00
2014-05-24 00:00:00
2014-05-25 00:00:00
2014-05-26 00:00:00
2014-05-27 00:00:00
2014-05-28 00:00:00
2014-05-29 00:00:00
2014-05-30 00:00:00
2014-05-31 00:00:00
2014-06-01 00:00:00
2014-06-02 00:00:00
2014-06-03 00:00:00
2014-06-04 00:00:00
2014-06-05 00:00:00
2014-06-06 00:00:00
2014-06-07 00:00:00
2014-06-08 00:00:00
2014-06-09 00:00:00
2014-06-10 00:00:00
2014-06-11 00:00:00
2014-06-12 00:00:00
2014-06-13 00:00:00
2014-06-14 00:00:00
2014-06-15 00:00:00
2014-06-16 00:00:00
2014-06-17 00:00:00
2014-06-18 00:00:00
2014-06-19 00:00:00
2014-06-20 00:00:00
2014-06-21 00:00:00
2014-06-22 00:00:00
2014-06-23 00:00:00
2014-06-24 00:00:00
2014-06-25 00:00:00
2014-06-26 00:00:00
2014-06-27 00:00:00
2014-06-28 00:00:00
2014-06-29 00:00:00
2014-06-30 00:00:00
2014-07-01 00:00:00
2014-07-02 00:00:00
2014-07-03 00:00:00
2014-07-04 00:00:00
2014-07-05 00:00:00
2014-07-06 00:00:00
2014-07-07 00:00:00
2014-07-08 00:00:00
2014-07-09 00:00:00
2014-07-10 00:00:00
2014-07-11 00:00:00
2014-07-12 00:00:00
2014-07-13 00:00:00
2014-07-14 00:00:00
2014-07-15 00:00:00
2014-07-16 00:00:00
2014-07-17 00:00:00
2014-07-18 00:00:00
2014-07-19 00:00:00
2014-07-20 00:00:00
2014-07-21 00:00:00
2014-07-22 00:00:00
2014-07-23 00:00:00
2014-07-24 00:00:00
2014-07-25 00:00:00
2014-07-26 00:00:00
2014-07-27 00:00:00
2014-07-28 00:00:00
2014-07-29 00:00:00
2014-07-30 00:00:00
2014-07-31 00:00:00
2014-08-01 00:00:00
2014-08-02 00:00:00
2014-08-03 00:00:00
2014-08-04 00:00:00
2014-08-05 00:00:00
2014-08-06 00:00:00
2014-08-07 00:00:00
2014-08-08 00:00:00
2014-08-09 00:00:00
2014-08-10 00:00:00
2014-08-11 00:00:00
2014-08-12 00:00:00
2014-08-13 00:00:00
2014-08-14 00:00:00
2014-08-15 00:00:00
2014-08-16 00:00:00
2014-08-17 00:00:00
2014-08-18 00:00:00
2014-08-19 00:00:00
2014-08-20 00:00:00
2014-08-21 00:00:00
2014-08-22 00:00:00
2014-08-23 00:00:00
2014-08-24 00:00:00
2014-08-25 00:00:00
2014-08-26 00:00:00
2014-08-27 00:00:00
2014-08-28 00:00:00
2014-08-29 00:00:00
2014-08-30 00:00:00
2014-08-31 00:00:00
2014-09-01 00:00:00
2014-09-02 00:00:00
2014-09-03 00:00:00
2014-09-04 00:00:00
2014-09-05 00:00:00
2014-09-06 00:00:00
2014-09-07 00:00:00
2014-09-08 00:00:00
2014-09-09 00:00:00
2014-09-10 00:00:00
2014-09-11 00:00:00
2014-09-12 00:00:00
2014-09-13 00:00:00
2014-09-14 00:00:00
2014-09-15 00:00:00
2014-09-16 00:00:00
2014-09-17 00:00:00
2014-09-18 00:00:00
2014-09-19 00:00:00
2014-09-20 00:00:00
2014-09-21 00:00:00
2014-09-22 00:00:00
2014-09-23 00:00:00
2014-09-24 00:00:00
2014-09-25 00:00:00
2014-09-26 00:00:00
2014-09-27 00:00:00
2014-09-28 00:00:00
2014-09-29 00:00:00
2014-09-30 00:00:00
2014-10-01 00:00:00
2014-10-02 00:00:00
2014-10-03 00:00:00
2014-10-04 00:00:00
2014-10-05 00:00:00
2014-10-06 00:00:00
2014-10-07 00:00:00
2014-10-08 00:00:00
2014-10-09 00:00:00
2014-10-10 00:00:00
2014-10-11 00:00:00
2014-10-12 00:00:00
2014-10-13 00:00:00
2014-10-14 00:00:00
2014-10-15 00:00:00
2014-10-16 00:00:00
2014-10-17 00:00:00
2014-10-18 00:00:00
2014-10-19 00:00:00
2014-10-20 00:00:00
2014-10-21 00:00:00
2014-10-22 00:00:00
2014-10-23 00:00:00
2014-10-24 00:00:00
2014-10-25 00:00:00
2014-10-26 00:00:00
2014-10-27 00:00:00
2014-10-28 00:00:00
2014-10-29 00:00:00
2014-10-30 00:00:00
2014-10-31 00:00:00
2014-11-01 00:00:00
2014-11-02 00:00:00
2014-11-03 00:00:00
2014-11-04 00:00:00
2014-11-05 00:00:00
2014-11-06 00:00:00
2014-11-07 00:00:00
2014-11-08 00:00:00
2014-11-09 00:00:00
2014-11-10 00:00:00
2014-11-11 00:00:00
2014-11-12 00:00:00
2014-11-13 00:00:00
2014-11-14 00:00:00
2014-11-15 00:00:00
2014-11-16 00:00:00
2014-11-17 00:00:00
2014-11-18 00:00:00
2014-11-19 00:00:00
2014-11-20 00:00:00
2014-11-21 00:00:00
2014-11-22 00:00:00
2014-11-23 00:00:00
2014-11-24 00:00:00
2014-11-25 00:00:00
2014-11-26 00:00:00
2014-11-27 00:00:00
2014-11-28 00:00:00
2014-11-29 00:00:00
2014-11-30 00:00:00
2014-12-01 00:00:00
2014-12-02 00:00:00
2014-12-03 00:00:00
2014-12-04 00:00:00
2014-12-05 00:00:00
2014-12-06 00:00:00
2014-12-07 00:00:00
2014-12-08 00:00:00
2014-12-09 00:00:00
2014-12-10 00:00:00
2014-12-11 00:00:00
2014-12-12 00:00:00
2014-12-13 00:00:00
2014-12-14 00:00:00
2014-12-15 00:00:00
2014-12-16 00:00:00
2014-12-17 00:00:00
2014-12-18 00:00:00
2014-12-19 00:00:00
2014-12-20 00:00:00
2014-12-21 00:00:00
2014-12-22 00:00:00
2014-12-23 00:00:00
2014-12-24 00:00:00
2014-12-25 00:00:00
2014-12-26 00:00:00
2014-12-27 00:00:00
2014-12-28 00:00:00
2014-12-29 00:00:00
2014-12-30 00:00:00
2014-12-31 00:00:00
2015-01-01 00:00:00

In [100]:
for index, row in df_gsr_filled.iterrows():
    print df_gsr_filled.iloc(index + timedelta(days = 1))

<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751BE0>
<pandas.core.indexing._iLocIndexer object at 0x0000000011751A20>

In [101]:
last = df_gsr_filled.irow(0)
for i in range(1, df_gsr_filled.shape[0]):
    print(last)
    print(df.irow(i))
    last = df.irow(i)

event    1
Name: 2014-01-01 00:00:00, dtype: float64

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: irow(i) is deprecated. Please use .iloc[i]
  if __name__ == '__main__':

NameError: name 'df' is not defined

In [102]:
last = df_gsr_filled.irow(0)
for i in range(1, df_gsr_filled.shape[0]):
    print(last)
    print(df_gsr_filled.iloc[i])
    last = df_gsr_filled.iloc[i]

event    1
Name: 2014-01-01 00:00:00, dtype: float64
event    1
Name: 2014-01-02 00:00:00, dtype: float64
event    1
Name: 2014-01-02 00:00:00, dtype: float64
event    1
Name: 2014-01-03 00:00:00, dtype: float64
event    1
Name: 2014-01-03 00:00:00, dtype: float64
event    1
Name: 2014-01-04 00:00:00, dtype: float64
event    1
Name: 2014-01-04 00:00:00, dtype: float64
event    1
Name: 2014-01-05 00:00:00, dtype: float64
event    1
Name: 2014-01-05 00:00:00, dtype: float64
event    1
Name: 2014-01-06 00:00:00, dtype: float64
event    1
Name: 2014-01-06 00:00:00, dtype: float64
event    1
Name: 2014-01-07 00:00:00, dtype: float64
event    1
Name: 2014-01-07 00:00:00, dtype: float64
event    1
Name: 2014-01-08 00:00:00, dtype: float64
event    1
Name: 2014-01-08 00:00:00, dtype: float64
event    1
Name: 2014-01-09 00:00:00, dtype: float64
event    1
Name: 2014-01-09 00:00:00, dtype: float64
event    1
Name: 2014-01-10 00:00:00, dtype: float64
event    1
Name: 2014-01-10 00:00:00, dtype: float64
event    1
Name: 2014-01-11 00:00:00, dtype: float64
event    1
Name: 2014-01-11 00:00:00, dtype: float64
event    1
Name: 2014-01-12 00:00:00, dtype: float64
event    1
Name: 2014-01-12 00:00:00, dtype: float64
event    1
Name: 2014-01-13 00:00:00, dtype: float64
event    1
Name: 2014-01-13 00:00:00, dtype: float64
event    1
Name: 2014-01-14 00:00:00, dtype: float64
event    1
Name: 2014-01-14 00:00:00, dtype: float64
event    1
Name: 2014-01-15 00:00:00, dtype: float64
event    1
Name: 2014-01-15 00:00:00, dtype: float64
event    1
Name: 2014-01-16 00:00:00, dtype: float64
event    1
Name: 2014-01-16 00:00:00, dtype: float64
event    1
Name: 2014-01-17 00:00:00, dtype: float64
event    1
Name: 2014-01-17 00:00:00, dtype: float64
event    1
Name: 2014-01-18 00:00:00, dtype: float64
event    1
Name: 2014-01-18 00:00:00, dtype: float64
event    1
Name: 2014-01-19 00:00:00, dtype: float64
event    1
Name: 2014-01-19 00:00:00, dtype: float64
event    1
Name: 2014-01-20 00:00:00, dtype: float64
event    1
Name: 2014-01-20 00:00:00, dtype: float64
event    1
Name: 2014-01-21 00:00:00, dtype: float64
event    1
Name: 2014-01-21 00:00:00, dtype: float64
event    1
Name: 2014-01-22 00:00:00, dtype: float64
event    1
Name: 2014-01-22 00:00:00, dtype: float64
event    1
Name: 2014-01-23 00:00:00, dtype: float64
event    1
Name: 2014-01-23 00:00:00, dtype: float64
event    1
Name: 2014-01-24 00:00:00, dtype: float64
event    1
Name: 2014-01-24 00:00:00, dtype: float64
event    1
Name: 2014-01-25 00:00:00, dtype: float64
event    1
Name: 2014-01-25 00:00:00, dtype: float64
event    1
Name: 2014-01-26 00:00:00, dtype: float64
event    1
Name: 2014-01-26 00:00:00, dtype: float64
event    1
Name: 2014-01-27 00:00:00, dtype: float64
event    1
Name: 2014-01-27 00:00:00, dtype: float64
event    1
Name: 2014-01-28 00:00:00, dtype: float64
event    1
Name: 2014-01-28 00:00:00, dtype: float64
event    1
Name: 2014-01-29 00:00:00, dtype: float64
event    1
Name: 2014-01-29 00:00:00, dtype: float64
event    1
Name: 2014-01-30 00:00:00, dtype: float64
event    1
Name: 2014-01-30 00:00:00, dtype: float64
event    1
Name: 2014-01-31 00:00:00, dtype: float64
event    1
Name: 2014-01-31 00:00:00, dtype: float64
event    1
Name: 2014-02-01 00:00:00, dtype: float64
event    1
Name: 2014-02-01 00:00:00, dtype: float64
event    1
Name: 2014-02-02 00:00:00, dtype: float64
event    1
Name: 2014-02-02 00:00:00, dtype: float64
event    1
Name: 2014-02-03 00:00:00, dtype: float64
event    1
Name: 2014-02-03 00:00:00, dtype: float64
event    1
Name: 2014-02-04 00:00:00, dtype: float64
event    1
Name: 2014-02-04 00:00:00, dtype: float64
event    1
Name: 2014-02-05 00:00:00, dtype: float64
event    1
Name: 2014-02-05 00:00:00, dtype: float64
event    1
Name: 2014-02-06 00:00:00, dtype: float64
event    1
Name: 2014-02-06 00:00:00, dtype: float64
event    1
Name: 2014-02-07 00:00:00, dtype: float64
event    1
Name: 2014-02-07 00:00:00, dtype: float64
event    1
Name: 2014-02-08 00:00:00, dtype: float64
event    1
Name: 2014-02-08 00:00:00, dtype: float64
event    1
Name: 2014-02-09 00:00:00, dtype: float64
event    1
Name: 2014-02-09 00:00:00, dtype: float64
event    1
Name: 2014-02-10 00:00:00, dtype: float64
event    1
Name: 2014-02-10 00:00:00, dtype: float64
event    1
Name: 2014-02-11 00:00:00, dtype: float64
event    1
Name: 2014-02-11 00:00:00, dtype: float64
event    1
Name: 2014-02-12 00:00:00, dtype: float64
event    1
Name: 2014-02-12 00:00:00, dtype: float64
event    1
Name: 2014-02-13 00:00:00, dtype: float64
event    1
Name: 2014-02-13 00:00:00, dtype: float64
event    1
Name: 2014-02-14 00:00:00, dtype: float64
event    1
Name: 2014-02-14 00:00:00, dtype: float64
event    1
Name: 2014-02-15 00:00:00, dtype: float64
event    1
Name: 2014-02-15 00:00:00, dtype: float64
event    1
Name: 2014-02-16 00:00:00, dtype: float64
event    1
Name: 2014-02-16 00:00:00, dtype: float64
event    1
Name: 2014-02-17 00:00:00, dtype: float64
event    1
Name: 2014-02-17 00:00:00, dtype: float64
event    1
Name: 2014-02-18 00:00:00, dtype: float64
event    1
Name: 2014-02-18 00:00:00, dtype: float64
event    1
Name: 2014-02-19 00:00:00, dtype: float64
event    1
Name: 2014-02-19 00:00:00, dtype: float64
event    1
Name: 2014-02-20 00:00:00, dtype: float64
event    1
Name: 2014-02-20 00:00:00, dtype: float64
event    1
Name: 2014-02-21 00:00:00, dtype: float64
event    1
Name: 2014-02-21 00:00:00, dtype: float64
event    1
Name: 2014-02-22 00:00:00, dtype: float64
event    1
Name: 2014-02-22 00:00:00, dtype: float64
event    1
Name: 2014-02-23 00:00:00, dtype: float64
event    1
Name: 2014-02-23 00:00:00, dtype: float64
event    1
Name: 2014-02-24 00:00:00, dtype: float64
event    1
Name: 2014-02-24 00:00:00, dtype: float64
event    1
Name: 2014-02-25 00:00:00, dtype: float64
event    1
Name: 2014-02-25 00:00:00, dtype: float64
event    1
Name: 2014-02-26 00:00:00, dtype: float64
event    1
Name: 2014-02-26 00:00:00, dtype: float64
event    1
Name: 2014-02-27 00:00:00, dtype: float64
event    1
Name: 2014-02-27 00:00:00, dtype: float64
event    1
Name: 2014-02-28 00:00:00, dtype: float64
event    1
Name: 2014-02-28 00:00:00, dtype: float64
event    1
Name: 2014-03-01 00:00:00, dtype: float64
event    1
Name: 2014-03-01 00:00:00, dtype: float64
event    1
Name: 2014-03-02 00:00:00, dtype: float64
event    1
Name: 2014-03-02 00:00:00, dtype: float64
event    1
Name: 2014-03-03 00:00:00, dtype: float64
event    1
Name: 2014-03-03 00:00:00, dtype: float64
event    1
Name: 2014-03-04 00:00:00, dtype: float64
event    1
Name: 2014-03-04 00:00:00, dtype: float64
event    1
Name: 2014-03-05 00:00:00, dtype: float64
event    1
Name: 2014-03-05 00:00:00, dtype: float64
event    1
Name: 2014-03-06 00:00:00, dtype: float64
event    1
Name: 2014-03-06 00:00:00, dtype: float64
event    1
Name: 2014-03-07 00:00:00, dtype: float64
event    1
Name: 2014-03-07 00:00:00, dtype: float64
event    1
Name: 2014-03-08 00:00:00, dtype: float64
event    1
Name: 2014-03-08 00:00:00, dtype: float64
event    1
Name: 2014-03-09 00:00:00, dtype: float64
event    1
Name: 2014-03-09 00:00:00, dtype: float64
event    1
Name: 2014-03-10 00:00:00, dtype: float64
event    1
Name: 2014-03-10 00:00:00, dtype: float64
event    1
Name: 2014-03-11 00:00:00, dtype: float64
event    1
Name: 2014-03-11 00:00:00, dtype: float64
event    1
Name: 2014-03-12 00:00:00, dtype: float64
event    1
Name: 2014-03-12 00:00:00, dtype: float64
event    1
Name: 2014-03-13 00:00:00, dtype: float64
event    1
Name: 2014-03-13 00:00:00, dtype: float64
event    1
Name: 2014-03-14 00:00:00, dtype: float64
event    1
Name: 2014-03-14 00:00:00, dtype: float64
event    1
Name: 2014-03-15 00:00:00, dtype: float64
event    1
Name: 2014-03-15 00:00:00, dtype: float64
event    1
Name: 2014-03-16 00:00:00, dtype: float64
event    1
Name: 2014-03-16 00:00:00, dtype: float64
event    1
Name: 2014-03-17 00:00:00, dtype: float64
event    1
Name: 2014-03-17 00:00:00, dtype: float64
event    1
Name: 2014-03-18 00:00:00, dtype: float64
event    1
Name: 2014-03-18 00:00:00, dtype: float64
event    1
Name: 2014-03-19 00:00:00, dtype: float64
event    1
Name: 2014-03-19 00:00:00, dtype: float64
event    1
Name: 2014-03-20 00:00:00, dtype: float64
event    1
Name: 2014-03-20 00:00:00, dtype: float64
event    1
Name: 2014-03-21 00:00:00, dtype: float64
event    1
Name: 2014-03-21 00:00:00, dtype: float64
event    1
Name: 2014-03-22 00:00:00, dtype: float64
event    1
Name: 2014-03-22 00:00:00, dtype: float64
event    1
Name: 2014-03-23 00:00:00, dtype: float64
event    1
Name: 2014-03-23 00:00:00, dtype: float64
event    1
Name: 2014-03-24 00:00:00, dtype: float64
event    1
Name: 2014-03-24 00:00:00, dtype: float64
event    1
Name: 2014-03-25 00:00:00, dtype: float64
event    1
Name: 2014-03-25 00:00:00, dtype: float64
event    1
Name: 2014-03-26 00:00:00, dtype: float64
event    1
Name: 2014-03-26 00:00:00, dtype: float64
event    1
Name: 2014-03-27 00:00:00, dtype: float64
event    1
Name: 2014-03-27 00:00:00, dtype: float64
event    1
Name: 2014-03-28 00:00:00, dtype: float64
event    1
Name: 2014-03-28 00:00:00, dtype: float64
event    1
Name: 2014-03-29 00:00:00, dtype: float64
event    1
Name: 2014-03-29 00:00:00, dtype: float64
event    1
Name: 2014-03-30 00:00:00, dtype: float64
event    1
Name: 2014-03-30 00:00:00, dtype: float64
event    1
Name: 2014-03-31 00:00:00, dtype: float64
event    1
Name: 2014-03-31 00:00:00, dtype: float64
event    1
Name: 2014-04-01 00:00:00, dtype: float64
event    1
Name: 2014-04-01 00:00:00, dtype: float64
event    1
Name: 2014-04-02 00:00:00, dtype: float64
event    1
Name: 2014-04-02 00:00:00, dtype: float64
event    1
Name: 2014-04-03 00:00:00, dtype: float64
event    1
Name: 2014-04-03 00:00:00, dtype: float64
event    1
Name: 2014-04-04 00:00:00, dtype: float64
event    1
Name: 2014-04-04 00:00:00, dtype: float64
event    1
Name: 2014-04-05 00:00:00, dtype: float64
event    1
Name: 2014-04-05 00:00:00, dtype: float64
event    1
Name: 2014-04-06 00:00:00, dtype: float64
event    1
Name: 2014-04-06 00:00:00, dtype: float64
event    1
Name: 2014-04-07 00:00:00, dtype: float64
event    1
Name: 2014-04-07 00:00:00, dtype: float64
event    1
Name: 2014-04-08 00:00:00, dtype: float64
event    1
Name: 2014-04-08 00:00:00, dtype: float64
event    1
Name: 2014-04-09 00:00:00, dtype: float64
event    1
Name: 2014-04-09 00:00:00, dtype: float64
event    1
Name: 2014-04-10 00:00:00, dtype: float64
event    1
Name: 2014-04-10 00:00:00, dtype: float64
event    1
Name: 2014-04-11 00:00:00, dtype: float64
event    1
Name: 2014-04-11 00:00:00, dtype: float64
event    1
Name: 2014-04-12 00:00:00, dtype: float64
event    1
Name: 2014-04-12 00:00:00, dtype: float64
event    1
Name: 2014-04-13 00:00:00, dtype: float64
event    1
Name: 2014-04-13 00:00:00, dtype: float64
event    1
Name: 2014-04-14 00:00:00, dtype: float64
event    1
Name: 2014-04-14 00:00:00, dtype: float64
event    1
Name: 2014-04-15 00:00:00, dtype: float64
event    1
Name: 2014-04-15 00:00:00, dtype: float64
event    1
Name: 2014-04-16 00:00:00, dtype: float64
event    1
Name: 2014-04-16 00:00:00, dtype: float64
event    1
Name: 2014-04-17 00:00:00, dtype: float64
event    1
Name: 2014-04-17 00:00:00, dtype: float64
event    1
Name: 2014-04-18 00:00:00, dtype: float64
event    1
Name: 2014-04-18 00:00:00, dtype: float64
event    1
Name: 2014-04-19 00:00:00, dtype: float64
event    1
Name: 2014-04-19 00:00:00, dtype: float64
event    1
Name: 2014-04-20 00:00:00, dtype: float64
event    1
Name: 2014-04-20 00:00:00, dtype: float64
event    1
Name: 2014-04-21 00:00:00, dtype: float64
event    1
Name: 2014-04-21 00:00:00, dtype: float64
event    1
Name: 2014-04-22 00:00:00, dtype: float64
event    1
Name: 2014-04-22 00:00:00, dtype: float64
event    1
Name: 2014-04-23 00:00:00, dtype: float64
event    1
Name: 2014-04-23 00:00:00, dtype: float64
event    1
Name: 2014-04-24 00:00:00, dtype: float64
event    1
Name: 2014-04-24 00:00:00, dtype: float64
event    1
Name: 2014-04-25 00:00:00, dtype: float64
event    1
Name: 2014-04-25 00:00:00, dtype: float64
event    1
Name: 2014-04-26 00:00:00, dtype: float64
event    1
Name: 2014-04-26 00:00:00, dtype: float64
event    1
Name: 2014-04-27 00:00:00, dtype: float64
event    1
Name: 2014-04-27 00:00:00, dtype: float64
event    1
Name: 2014-04-28 00:00:00, dtype: float64
event    1
Name: 2014-04-28 00:00:00, dtype: float64
event    1
Name: 2014-04-29 00:00:00, dtype: float64
event    1
Name: 2014-04-29 00:00:00, dtype: float64
event    1
Name: 2014-04-30 00:00:00, dtype: float64
event    1
Name: 2014-04-30 00:00:00, dtype: float64
event    1
Name: 2014-05-01 00:00:00, dtype: float64
event    1
Name: 2014-05-01 00:00:00, dtype: float64
event    1
Name: 2014-05-02 00:00:00, dtype: float64
event    1
Name: 2014-05-02 00:00:00, dtype: float64
event    1
Name: 2014-05-03 00:00:00, dtype: float64
event    1
Name: 2014-05-03 00:00:00, dtype: float64
event    1
Name: 2014-05-04 00:00:00, dtype: float64
event    1
Name: 2014-05-04 00:00:00, dtype: float64
event    1
Name: 2014-05-05 00:00:00, dtype: float64
event    1
Name: 2014-05-05 00:00:00, dtype: float64
event    1
Name: 2014-05-06 00:00:00, dtype: float64
event    1
Name: 2014-05-06 00:00:00, dtype: float64
event    1
Name: 2014-05-07 00:00:00, dtype: float64
event    1
Name: 2014-05-07 00:00:00, dtype: float64
event    1
Name: 2014-05-08 00:00:00, dtype: float64
event    1
Name: 2014-05-08 00:00:00, dtype: float64
event    1
Name: 2014-05-09 00:00:00, dtype: float64
event    1
Name: 2014-05-09 00:00:00, dtype: float64
event    1
Name: 2014-05-10 00:00:00, dtype: float64
event    1
Name: 2014-05-10 00:00:00, dtype: float64
event   NaN
Name: 2014-05-11 00:00:00, dtype: float64
event   NaN
Name: 2014-05-11 00:00:00, dtype: float64
event    1
Name: 2014-05-12 00:00:00, dtype: float64
event    1
Name: 2014-05-12 00:00:00, dtype: float64
event    1
Name: 2014-05-13 00:00:00, dtype: float64
event    1
Name: 2014-05-13 00:00:00, dtype: float64
event    1
Name: 2014-05-14 00:00:00, dtype: float64
event    1
Name: 2014-05-14 00:00:00, dtype: float64
event    1
Name: 2014-05-15 00:00:00, dtype: float64
event    1
Name: 2014-05-15 00:00:00, dtype: float64
event    1
Name: 2014-05-16 00:00:00, dtype: float64
event    1
Name: 2014-05-16 00:00:00, dtype: float64
event    1
Name: 2014-05-17 00:00:00, dtype: float64
event    1
Name: 2014-05-17 00:00:00, dtype: float64
event    1
Name: 2014-05-18 00:00:00, dtype: float64
event    1
Name: 2014-05-18 00:00:00, dtype: float64
event    1
Name: 2014-05-19 00:00:00, dtype: float64
event    1
Name: 2014-05-19 00:00:00, dtype: float64
event    1
Name: 2014-05-20 00:00:00, dtype: float64
event    1
Name: 2014-05-20 00:00:00, dtype: float64
event    1
Name: 2014-05-21 00:00:00, dtype: float64
event    1
Name: 2014-05-21 00:00:00, dtype: float64
event    1
Name: 2014-05-22 00:00:00, dtype: float64
event    1
Name: 2014-05-22 00:00:00, dtype: float64
event    1
Name: 2014-05-23 00:00:00, dtype: float64
event    1
Name: 2014-05-23 00:00:00, dtype: float64
event    1
Name: 2014-05-24 00:00:00, dtype: float64
event    1
Name: 2014-05-24 00:00:00, dtype: float64
event    1
Name: 2014-05-25 00:00:00, dtype: float64
event    1
Name: 2014-05-25 00:00:00, dtype: float64
event    1
Name: 2014-05-26 00:00:00, dtype: float64
event    1
Name: 2014-05-26 00:00:00, dtype: float64
event    1
Name: 2014-05-27 00:00:00, dtype: float64
event    1
Name: 2014-05-27 00:00:00, dtype: float64
event    1
Name: 2014-05-28 00:00:00, dtype: float64
event    1
Name: 2014-05-28 00:00:00, dtype: float64
event    1
Name: 2014-05-29 00:00:00, dtype: float64
event    1
Name: 2014-05-29 00:00:00, dtype: float64
event    1
Name: 2014-05-30 00:00:00, dtype: float64
event    1
Name: 2014-05-30 00:00:00, dtype: float64
event    1
Name: 2014-05-31 00:00:00, dtype: float64
event    1
Name: 2014-05-31 00:00:00, dtype: float64
event    1
Name: 2014-06-01 00:00:00, dtype: float64
event    1
Name: 2014-06-01 00:00:00, dtype: float64
event    1
Name: 2014-06-02 00:00:00, dtype: float64
event    1
Name: 2014-06-02 00:00:00, dtype: float64
event    1
Name: 2014-06-03 00:00:00, dtype: float64
event    1
Name: 2014-06-03 00:00:00, dtype: float64
event    1
Name: 2014-06-04 00:00:00, dtype: float64
event    1
Name: 2014-06-04 00:00:00, dtype: float64
event    1
Name: 2014-06-05 00:00:00, dtype: float64
event    1
Name: 2014-06-05 00:00:00, dtype: float64
event    1
Name: 2014-06-06 00:00:00, dtype: float64
event    1
Name: 2014-06-06 00:00:00, dtype: float64
event    1
Name: 2014-06-07 00:00:00, dtype: float64
event    1
Name: 2014-06-07 00:00:00, dtype: float64
event    1
Name: 2014-06-08 00:00:00, dtype: float64
event    1
Name: 2014-06-08 00:00:00, dtype: float64
event    1
Name: 2014-06-09 00:00:00, dtype: float64
event    1
Name: 2014-06-09 00:00:00, dtype: float64
event    1
Name: 2014-06-10 00:00:00, dtype: float64
event    1
Name: 2014-06-10 00:00:00, dtype: float64
event    1
Name: 2014-06-11 00:00:00, dtype: float64
event    1
Name: 2014-06-11 00:00:00, dtype: float64
event    1
Name: 2014-06-12 00:00:00, dtype: float64
event    1
Name: 2014-06-12 00:00:00, dtype: float64
event    1
Name: 2014-06-13 00:00:00, dtype: float64
event    1
Name: 2014-06-13 00:00:00, dtype: float64
event    1
Name: 2014-06-14 00:00:00, dtype: float64
event    1
Name: 2014-06-14 00:00:00, dtype: float64
event    1
Name: 2014-06-15 00:00:00, dtype: float64
event    1
Name: 2014-06-15 00:00:00, dtype: float64
event    1
Name: 2014-06-16 00:00:00, dtype: float64
event    1
Name: 2014-06-16 00:00:00, dtype: float64
event    1
Name: 2014-06-17 00:00:00, dtype: float64
event    1
Name: 2014-06-17 00:00:00, dtype: float64
event    1
Name: 2014-06-18 00:00:00, dtype: float64
event    1
Name: 2014-06-18 00:00:00, dtype: float64
event    1
Name: 2014-06-19 00:00:00, dtype: float64
event    1
Name: 2014-06-19 00:00:00, dtype: float64
event    1
Name: 2014-06-20 00:00:00, dtype: float64
event    1
Name: 2014-06-20 00:00:00, dtype: float64
event    1
Name: 2014-06-21 00:00:00, dtype: float64
event    1
Name: 2014-06-21 00:00:00, dtype: float64
event    1
Name: 2014-06-22 00:00:00, dtype: float64
event    1
Name: 2014-06-22 00:00:00, dtype: float64
event    1
Name: 2014-06-23 00:00:00, dtype: float64
event    1
Name: 2014-06-23 00:00:00, dtype: float64
event    1
Name: 2014-06-24 00:00:00, dtype: float64
event    1
Name: 2014-06-24 00:00:00, dtype: float64
event    1
Name: 2014-06-25 00:00:00, dtype: float64
event    1
Name: 2014-06-25 00:00:00, dtype: float64
event    1
Name: 2014-06-26 00:00:00, dtype: float64
event    1
Name: 2014-06-26 00:00:00, dtype: float64
event    1
Name: 2014-06-27 00:00:00, dtype: float64
event    1
Name: 2014-06-27 00:00:00, dtype: float64
event    1
Name: 2014-06-28 00:00:00, dtype: float64
event    1
Name: 2014-06-28 00:00:00, dtype: float64
event    1
Name: 2014-06-29 00:00:00, dtype: float64
event    1
Name: 2014-06-29 00:00:00, dtype: float64
event    1
Name: 2014-06-30 00:00:00, dtype: float64
event    1
Name: 2014-06-30 00:00:00, dtype: float64
event    1
Name: 2014-07-01 00:00:00, dtype: float64
event    1
Name: 2014-07-01 00:00:00, dtype: float64
event    1
Name: 2014-07-02 00:00:00, dtype: float64
event    1
Name: 2014-07-02 00:00:00, dtype: float64
event    1
Name: 2014-07-03 00:00:00, dtype: float64
event    1
Name: 2014-07-03 00:00:00, dtype: float64
event    1
Name: 2014-07-04 00:00:00, dtype: float64
event    1
Name: 2014-07-04 00:00:00, dtype: float64
event    1
Name: 2014-07-05 00:00:00, dtype: float64
event    1
Name: 2014-07-05 00:00:00, dtype: float64
event    1
Name: 2014-07-06 00:00:00, dtype: float64
event    1
Name: 2014-07-06 00:00:00, dtype: float64
event    1
Name: 2014-07-07 00:00:00, dtype: float64
event    1
Name: 2014-07-07 00:00:00, dtype: float64
event    1
Name: 2014-07-08 00:00:00, dtype: float64
event    1
Name: 2014-07-08 00:00:00, dtype: float64
event    1

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: irow(i) is deprecated. Please use .iloc[i]
  if __name__ == '__main__':

In [103]:
import pandas as pd
import numpy as np
import json as js
from datetime import datetime,timedelta

file_gsr = "./gsrAll.json"

min_date = datetime(2014,1,1)
max_date = datetime(2014,12,31)

df_gsr = pd.DataFrame(columns=('date', 'event'))
Lines = open(file_gsr).readlines()
for i in range(len(lines)):
    obj = js.loads(lines[i])
    if obj['location'][0] == 'Brazil':
        df_gsr.loc[i] = [datetime.strptime(obj['eventDate'].split("T")[0],'%Y-%m-%d') + timedelata(days = -1), 1]

df_gsr_selected = df_gsr[(df_gsr.date >= min_date)&(df_gsr.date <= max_date)]
df_gsr_aggregated = df_gsr_selected.groupby("date").agg({'event':lambda x: 1})
new_index = [min_date + timedelta(days = i) for i in range((max_date - min_date).days + 1)]
df_gsr_filled = df_gsr_aggregated.reindex(new_index)
df_gsr_filled.fillna(0)

NameError: name 'timedelata' is not defined

In [104]:
import pandas as pd
import numpy as np
import json as js
from datetime import datetime,timedelta

file_gsr = "./gsrAll.json"

min_date = datetime(2014,1,1)
max_date = datetime(2014,12,31)

df_gsr = pd.DataFrame(columns=('date', 'event'))
Lines = open(file_gsr).readlines()
for i in range(len(lines)):
    obj = js.loads(lines[i])
    if obj['location'][0] == 'Brazil':
        df_gsr.loc[i] = [datetime.strptime(obj['eventDate'].split("T")[0],'%Y-%m-%d') + timedelta(days = -1), 1]

df_gsr_selected = df_gsr[(df_gsr.date >= min_date)&(df_gsr.date <= max_date)]
df_gsr_aggregated = df_gsr_selected.groupby("date").agg({'event':lambda x: 1})
new_index = [min_date + timedelta(days = i) for i in range((max_date - min_date).days + 1)]
df_gsr_filled = df_gsr_aggregated.reindex(new_index)
df_gsr_filled.fillna(0)

            event
date
2014-01-01      1
2014-01-02      1
2014-01-03      1
2014-01-04      1
2014-01-05      1
2014-01-06      1
2014-01-07      1
2014-01-08      1
2014-01-09      1
2014-01-10      1
2014-01-11      1
2014-01-12      1
2014-01-13      1
2014-01-14      1
2014-01-15      1
2014-01-16      1
2014-01-17      1
2014-01-18      1
2014-01-19      1
2014-01-20      1
2014-01-21      1
2014-01-22      1
2014-01-23      1
2014-01-24      1
2014-01-25      1
2014-01-26      1
2014-01-27      1
2014-01-28      1
2014-01-29      1
2014-01-30      1
...           ...
2014-12-02      1
2014-12-03      1
2014-12-04      1
2014-12-05      1
2014-12-06      1
2014-12-07      1
2014-12-08      1
2014-12-09      1
2014-12-10      1
2014-12-11      1
2014-12-12      1
2014-12-13      1
2014-12-14      1
2014-12-15      1
2014-12-16      1
2014-12-17      1
2014-12-18      1
2014-12-19      0
2014-12-20      0
2014-12-21      1
2014-12-22      0
2014-12-23      1
2014-12-24      0
2014-12-25      1
2014-12-26      0
2014-12-27      0
2014-12-28      1
2014-12-29      0
2014-12-30      1
2014-12-31      1

[365 rows x 1 columns]

In [105]:
import pandas as pd
import numpy as np
import json as js
from datetime import datetime,timedelta

file_gsr = "./gsrAll.json"

min_date = datetime(2014,1,1)
max_date = datetime(2014,12,31)

df_gsr = pd.DataFrame(columns=('date', 'event'))
Lines = open(file_gsr).readlines()
for i in range(len(lines)):
    obj = js.loads(lines[i])
    if obj['location'][0] == 'Brazil':
        df_gsr.loc[i] = [datetime.strptime(obj['eventDate'].split("T")[0],'%Y-%m-%d'), 1]

df_gsr_selected = df_gsr[(df_gsr.date >= min_date)&(df_gsr.date <= max_date)]
df_gsr_aggregated = df_gsr_selected.groupby("date").agg({'event':lambda x: 1})
new_index = [min_date + timedelta(days = i) for i in range((max_date - min_date).days + 1)]
df_gsr_filled = df_gsr_aggregated.reindex(new_index)
df_gsr_filled.fillna(0)

            event
date
2014-01-01      1
2014-01-02      1
2014-01-03      1
2014-01-04      1
2014-01-05      1
2014-01-06      1
2014-01-07      1
2014-01-08      1
2014-01-09      1
2014-01-10      1
2014-01-11      1
2014-01-12      1
2014-01-13      1
2014-01-14      1
2014-01-15      1
2014-01-16      1
2014-01-17      1
2014-01-18      1
2014-01-19      1
2014-01-20      1
2014-01-21      1
2014-01-22      1
2014-01-23      1
2014-01-24      1
2014-01-25      1
2014-01-26      1
2014-01-27      1
2014-01-28      1
2014-01-29      1
2014-01-30      1
...           ...
2014-12-02      1
2014-12-03      1
2014-12-04      1
2014-12-05      1
2014-12-06      1
2014-12-07      1
2014-12-08      1
2014-12-09      1
2014-12-10      1
2014-12-11      1
2014-12-12      1
2014-12-13      1
2014-12-14      1
2014-12-15      1
2014-12-16      1
2014-12-17      1
2014-12-18      1
2014-12-19      1
2014-12-20      0
2014-12-21      0
2014-12-22      1
2014-12-23      0
2014-12-24      1
2014-12-25      0
2014-12-26      1
2014-12-27      0
2014-12-28      0
2014-12-29      1
2014-12-30      0
2014-12-31      1

[365 rows x 1 columns]